<b><h1><center>Data Gathering</center></h1></b>

# **Importing Data**

In [1]:
import pandas as pd

C:\Users\HP\AppData\Roaming\Python\Python313\site-packages\pandas\core\computation\expressions.py:22: UserWarning: Pandas requires version '2.10.2' or newer of 'numexpr' (version '2.10.1' currently installed).
  from pandas.core.computation.check import NUMEXPR_INSTALLED

# **Import CSV**

### **Opening a local csv file**

In [2]:
pd.read_csv('data/27_data/aug_train.csv').head()

,enrollee_id,city,city_development_index,gender,relevent_experience,enrolled_university,education_level,major_discipline,experience,company_size,company_type,last_new_job,training_hours,target
0,8949,city_103,0.920,Male,Has relevent experience,no_enrollment,Graduate,STEM,>20,NaN,NaN,1,36,1.0
1,29725,city_40,0.776,Male,No relevent experience,no_enrollment,Graduate,STEM,15,50-99,Pvt Ltd,>4,47,0.0
2,11561,city_21,0.624,NaN,No relevent experience,Full time course,Graduate,STEM,5,NaN,NaN,never,83,0.0
3,33241,city_115,0.789,NaN,No relevent experience,NaN,Graduate,Business Degree,<1,NaN,Pvt Ltd,never,52,1.0
4,666,city_162,0.767,Male,Has relevent experience,no_enrollment,Masters,STEM,>20,50-99,Funded Startup,4,8,0.0

### **Opening a csv file from an URL**

In [3]:

url = "https://raw.githubusercontent.com/cs109/2014_data/master/countries.csv"
pd.read_csv(url)

       Country         Region
0      Algeria         AFRICA
1       Angola         AFRICA
2        Benin         AFRICA
3     Botswana         AFRICA
4      Burkina         AFRICA
..         ...            ...
189   Paraguay  SOUTH AMERICA
190       Peru  SOUTH AMERICA
191   Suriname  SOUTH AMERICA
192    Uruguay  SOUTH AMERICA
193  Venezuela  SOUTH AMERICA

[194 rows x 2 columns]

### **Sep Parameter**

In [4]:
pd.read_csv('data/27_data/movie_titles_metadata.tsv',sep='\t', names=['sno','name','release_year','rating','votes','genres'])

,sno,name,release_year,rating,votes,genres
0,m0,10 things i hate about you,1999,6.9,62847.0,['comedy' 'romance']
1,m1,1492: conquest of paradise,1992,6.2,10421.0,['adventure' 'biography' 'drama' 'history']
2,m2,15 minutes,2001,6.1,25854.0,['action' 'crime' 'drama' 'thriller']
3,m3,2001: a space odyssey,1968,8.4,163227.0,['adventure' 'mystery' 'sci-fi']
4,m4,48 hrs.,1982,6.9,22289.0,['action' 'comedy' 'crime' 'drama' 'thriller']
...,...,...,...,...,...,...
612,m612,watchmen,2009,7.8,135229.0,['action' 'crime' 'fantasy' 'mystery' 'sci-fi'...
613,m613,xxx,2002,5.6,53505.0,['action' 'adventure' 'crime']
614,m614,x-men,2000,7.4,122149.0,['action' 'sci-fi']
615,m615,young frankenstein,1974,8.0,57618.0,['comedy' 'sci-fi']
616,m616,zulu dawn,1979,6.4,1911.0,['action' 'adventure' 'drama' 'history' 'war']

### **Index_col parameter**

In [5]:
pd.read_csv('data/27_data/aug_train.csv',index_col='enrollee_id')

,city,city_development_index,gender,relevent_experience,enrolled_university,education_level,major_discipline,experience,company_size,company_type,last_new_job,training_hours,target
enrollee_id,,,,,,,,,,,,,
8949,city_103,0.920,Male,Has relevent experience,no_enrollment,Graduate,STEM,>20,NaN,NaN,1,36,1.0
29725,city_40,0.776,Male,No relevent experience,no_enrollment,Graduate,STEM,15,50-99,Pvt Ltd,>4,47,0.0
11561,city_21,0.624,NaN,No relevent experience,Full time course,Graduate,STEM,5,NaN,NaN,never,83,0.0
33241,city_115,0.789,NaN,No relevent experience,NaN,Graduate,Business Degree,<1,NaN,Pvt Ltd,never,52,1.0
666,city_162,0.767,Male,Has relevent experience,no_enrollment,Masters,STEM,>20,50-99,Funded Startup,4,8,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...
7386,city_173,0.878,Male,No relevent experience,no_enrollment,Graduate,Humanities,14,NaN,NaN,1,42,1.0
31398,city_103,0.920,Male,Has relevent experience,no_enrollment,Graduate,STEM,14,NaN,NaN,4,52,1.0
24576,city_103,0.920,Male,Has relevent experience,no_enrollment,Graduate,STEM,>20,50-99,Pvt Ltd,4,44,0.0
5756,city_65,0.802,Male,Has relevent experience,no_enrollment,High School,NaN,<1,500-999,Pvt Ltd,2,97,0.0
23834,city_67,0.855,NaN,No relevent experience,no_enrollment,Primary School,NaN,2,NaN,NaN,1,127,0.0

### **Header parameter**

In [6]:
# it is used when i want to make the row as columns
pd.read_csv('data/27_data/test.csv',header=1)

,0,enrollee_id,city,city_development_index,gender,relevent_experience,enrolled_university,education_level,major_discipline,experience,company_size,company_type,last_new_job,training_hours,target
0,1,29725,city_40,0.776,Male,No relevent experience,no_enrollment,Graduate,STEM,15,50-99,Pvt Ltd,>4,47,0
1,2,11561,city_21,0.624,NaN,No relevent experience,Full time course,Graduate,STEM,5,NaN,NaN,never,83,0
2,3,33241,city_115,0.789,NaN,No relevent experience,NaN,Graduate,Business Degree,<1,NaN,Pvt Ltd,never,52,1
3,4,666,city_162,0.767,Male,Has relevent experience,no_enrollment,Masters,STEM,>20,50-99,Funded Startup,4,8,0

### **use_cols parameter**

In [7]:
pd.read_csv('data/27_data/aug_train.csv',usecols=['enrollee_id','gender','education_level'])

       enrollee_id gender education_level
0             8949   Male        Graduate
1            29725   Male        Graduate
2            11561    NaN        Graduate
3            33241    NaN        Graduate
4              666   Male         Masters
...            ...    ...             ...
19153         7386   Male        Graduate
19154        31398   Male        Graduate
19155        24576   Male        Graduate
19156         5756   Male     High School
19157        23834    NaN  Primary School

[19158 rows x 3 columns]

### **Squeeze parameters**

In [8]:
# convert dataframe into series
pd.read_csv('data/27_data/aug_train.csv',usecols=['gender']).squeeze()

0        Male
1        Male
2         NaN
3         NaN
4        Male
         ...
19153    Male
19154    Male
19155    Male
19156    Male
19157     NaN
Name: gender, Length: 19158, dtype: str

### **nrows Parameter**

In [9]:
pd.read_csv('data/27_data/aug_train.csv',nrows=100)

,enrollee_id,city,city_development_index,gender,relevent_experience,enrolled_university,education_level,major_discipline,experience,company_size,company_type,last_new_job,training_hours,target
0,8949,city_103,0.920,Male,Has relevent experience,no_enrollment,Graduate,STEM,>20,NaN,NaN,1,36,1.0
1,29725,city_40,0.776,Male,No relevent experience,no_enrollment,Graduate,STEM,15,50-99,Pvt Ltd,>4,47,0.0
2,11561,city_21,0.624,NaN,No relevent experience,Full time course,Graduate,STEM,5,NaN,NaN,never,83,0.0
3,33241,city_115,0.789,NaN,No relevent experience,NaN,Graduate,Business Degree,<1,NaN,Pvt Ltd,never,52,1.0
4,666,city_162,0.767,Male,Has relevent experience,no_enrollment,Masters,STEM,>20,50-99,Funded Startup,4,8,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
95,12081,city_65,0.802,Male,Has relevent experience,Full time course,Graduate,STEM,9,50-99,Pvt Ltd,1,33,0.0
96,7364,city_160,0.920,NaN,No relevent experience,Full time course,High School,NaN,2,100-500,Pvt Ltd,1,142,0.0
97,11184,city_74,0.579,NaN,No relevent experience,Full time course,Graduate,STEM,2,100-500,Pvt Ltd,1,34,0.0
98,7016,city_65,0.802,Male,Has relevent experience,no_enrollment,Graduate,STEM,6,50-99,Pvt Ltd,2,14,1.0
99,8695,city_11,0.550,Male,Has relevent experience,no_enrollment,Graduate,STEM,6,10/49,Pvt Ltd,2,27,1.0

### **Encoding parameter**

In [10]:
pd.read_csv('data/27_data/zomato.csv', encoding='latin-1').head()

,Restaurant ID,Restaurant Name,Country Code,City,Address,Locality,Locality Verbose,Longitude,Latitude,Cuisines,...,Currency,Has Table booking,Has Online delivery,Is delivering now,Switch to order menu,Price range,Aggregate rating,Rating color,Rating text,Votes
0,6317637,Le Petit Souffle,162,Makati City,"Third Floor, Century City Mall, Kalayaan Avenu...","Century City Mall, Poblacion, Makati City","Century City Mall, Poblacion, Makati City, Mak...",121.027535,14.565443,"French, Japanese, Desserts",...,Botswana Pula(P),Yes,No,No,No,3,4.8,Dark Green,Excellent,314
1,6304287,Izakaya Kikufuji,162,Makati City,"Little Tokyo, 2277 Chino Roces Avenue, Legaspi...","Little Tokyo, Legaspi Village, Makati City","Little Tokyo, Legaspi Village, Makati City, Ma...",121.014101,14.553708,Japanese,...,Botswana Pula(P),Yes,No,No,No,3,4.5,Dark Green,Excellent,591
2,6300002,Heat - Edsa Shangri-La,162,Mandaluyong City,"Edsa Shangri-La, 1 Garden Way, Ortigas, Mandal...","Edsa Shangri-La, Ortigas, Mandaluyong City","Edsa Shangri-La, Ortigas, Mandaluyong City, Ma...",121.056831,14.581404,"Seafood, Asian, Filipino, Indian",...,Botswana Pula(P),Yes,No,No,No,4,4.4,Green,Very Good,270
3,6318506,Ooma,162,Mandaluyong City,"Third Floor, Mega Fashion Hall, SM Megamall, O...","SM Megamall, Ortigas, Mandaluyong City","SM Megamall, Ortigas, Mandaluyong City, Mandal...",121.056475,14.585318,"Japanese, Sushi",...,Botswana Pula(P),No,No,No,No,4,4.9,Dark Green,Excellent,365
4,6314302,Sambo Kojin,162,Mandaluyong City,"Third Floor, Mega Atrium, SM Megamall, Ortigas...","SM Megamall, Ortigas, Mandaluyong City","SM Megamall, Ortigas, Mandaluyong City, Mandal...",121.057508,14.584450,"Japanese, Korean",...,Botswana Pula(P),Yes,No,No,No,4,4.8,Dark Green,Excellent,229

### **dtypes parameter**

In [11]:
pd.read_csv('data/27_data/aug_train.csv',dtype={'target':int}).info()

<class 'pandas.DataFrame'>
RangeIndex: 19158 entries, 0 to 19157
Data columns (total 14 columns):
 #   Column                  Non-Null Count  Dtype
---  ------                  --------------  -----
 0   enrollee_id             19158 non-null  int64
 1   city                    19158 non-null  str
 2   city_development_index  19158 non-null  float64
 3   gender                  14650 non-null  str
 4   relevent_experience     19158 non-null  str
 5   enrolled_university     18772 non-null  str
 6   education_level         18698 non-null  str
 7   major_discipline        16345 non-null  str
 8   experience              19093 non-null  str
 9   company_size            13220 non-null  str
 10  company_type            13018 non-null  str
 11  last_new_job            18735 non-null  str
 12  training_hours          19158 non-null  int64
 13  target                  19158 non-null  int64
dtypes: float64(1), int64(3), str(10)
memory usage: 3.4 MB

### **Handling Dates**

In [12]:
pd.read_csv('data/27_data/IPL Matches 2008-2020.csv',parse_dates=['date']).info()

<class 'pandas.DataFrame'>
RangeIndex: 816 entries, 0 to 815
Data columns (total 17 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   id               816 non-null    int64
 1   city             803 non-null    str
 2   date             816 non-null    datetime64[us]
 3   player_of_match  812 non-null    str
 4   venue            816 non-null    str
 5   neutral_venue    816 non-null    int64
 6   team1            816 non-null    str
 7   team2            816 non-null    str
 8   toss_winner      816 non-null    str
 9   toss_decision    816 non-null    str
 10  winner           812 non-null    str
 11  result           812 non-null    str
 12  result_margin    799 non-null    float64
 13  eliminator       812 non-null    str
 14  method           19 non-null     str
 15  umpire1          816 non-null    str
 16  umpire2          816 non-null    str
dtypes: datetime64[us](1), float64(1), int64(2), str(13)
memory usage: 225.0 KB

In [13]:
def rename(name):
    if name == "Royal Challengers Bangalore":
        return "RCB"
    else:
        return name

In [14]:
rename("Royal Challengers Bangalore")

'RCB'

### **Convertors**

In [15]:
pd.read_csv('data/27_data/IPL Matches 2008-2020.csv',converters={'team1':rename})

,id,city,date,player_of_match,venue,neutral_venue,team1,team2,toss_winner,toss_decision,winner,result,result_margin,eliminator,method,umpire1,umpire2
0,335982,Bangalore,2008-04-18,BB McCullum,M Chinnaswamy Stadium,0,RCB,Kolkata Knight Riders,Royal Challengers Bangalore,field,Kolkata Knight Riders,runs,140.0,N,NaN,Asad Rauf,RE Koertzen
1,335983,Chandigarh,2008-04-19,MEK Hussey,"Punjab Cricket Association Stadium, Mohali",0,Kings XI Punjab,Chennai Super Kings,Chennai Super Kings,bat,Chennai Super Kings,runs,33.0,N,NaN,MR Benson,SL Shastri
2,335984,Delhi,2008-04-19,MF Maharoof,Feroz Shah Kotla,0,Delhi Daredevils,Rajasthan Royals,Rajasthan Royals,bat,Delhi Daredevils,wickets,9.0,N,NaN,Aleem Dar,GA Pratapkumar
3,335985,Mumbai,2008-04-20,MV Boucher,Wankhede Stadium,0,Mumbai Indians,Royal Challengers Bangalore,Mumbai Indians,bat,Royal Challengers Bangalore,wickets,5.0,N,NaN,SJ Davis,DJ Harper
4,335986,Kolkata,2008-04-20,DJ Hussey,Eden Gardens,0,Kolkata Knight Riders,Deccan Chargers,Deccan Chargers,bat,Kolkata Knight Riders,wickets,5.0,N,NaN,BF Bowden,K Hariharan
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
811,1216547,Dubai,2020-09-28,AB de Villiers,Dubai International Cricket Stadium,0,RCB,Mumbai Indians,Mumbai Indians,field,Royal Challengers Bangalore,tie,NaN,Y,NaN,Nitin Menon,PR Reiffel
812,1237177,Dubai,2020-11-05,JJ Bumrah,Dubai International Cricket Stadium,0,Mumbai Indians,Delhi Capitals,Delhi Capitals,field,Mumbai Indians,runs,57.0,N,NaN,CB Gaffaney,Nitin Menon
813,1237178,Abu Dhabi,2020-11-06,KS Williamson,Sheikh Zayed Stadium,0,RCB,Sunrisers Hyderabad,Sunrisers Hyderabad,field,Sunrisers Hyderabad,wickets,6.0,N,NaN,PR Reiffel,S Ravi
814,1237180,Abu Dhabi,2020-11-08,MP Stoinis,Sheikh Zayed Stadium,0,Delhi Capitals,Sunrisers Hyderabad,Delhi Capitals,bat,Delhi Capitals,runs,17.0,N,NaN,PR Reiffel,S Ravi
815,1237181,Dubai,2020-11-10,TA Boult,Dubai International Cricket Stadium,0,Delhi Capitals,Mumbai Indians,Delhi Capitals,bat,Mumbai Indians,wickets,5.0,N,NaN,CB Gaffaney,Nitin Menon

### **na_values parameter**

In [16]:
pd.read_csv('data/27_data/aug_train.csv',na_values=['Male'])

,enrollee_id,city,city_development_index,gender,relevent_experience,enrolled_university,education_level,major_discipline,experience,company_size,company_type,last_new_job,training_hours,target
0,8949,city_103,0.920,NaN,Has relevent experience,no_enrollment,Graduate,STEM,>20,NaN,NaN,1,36,1.0
1,29725,city_40,0.776,NaN,No relevent experience,no_enrollment,Graduate,STEM,15,50-99,Pvt Ltd,>4,47,0.0
2,11561,city_21,0.624,NaN,No relevent experience,Full time course,Graduate,STEM,5,NaN,NaN,never,83,0.0
3,33241,city_115,0.789,NaN,No relevent experience,NaN,Graduate,Business Degree,<1,NaN,Pvt Ltd,never,52,1.0
4,666,city_162,0.767,NaN,Has relevent experience,no_enrollment,Masters,STEM,>20,50-99,Funded Startup,4,8,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
19153,7386,city_173,0.878,NaN,No relevent experience,no_enrollment,Graduate,Humanities,14,NaN,NaN,1,42,1.0
19154,31398,city_103,0.920,NaN,Has relevent experience,no_enrollment,Graduate,STEM,14,NaN,NaN,4,52,1.0
19155,24576,city_103,0.920,NaN,Has relevent experience,no_enrollment,Graduate,STEM,>20,50-99,Pvt Ltd,4,44,0.0
19156,5756,city_65,0.802,NaN,Has relevent experience,no_enrollment,High School,NaN,<1,500-999,Pvt Ltd,2,97,0.0
19157,23834,city_67,0.855,NaN,No relevent experience,no_enrollment,Primary School,NaN,2,NaN,NaN,1,127,0.0

<br>

# **Import Text File**

In [17]:
pd.read_csv('data/27_data/movie_titles_metadata.tsv', sep='\t')

,m0,10 things i hate about you,1999,6.90,62847,['comedy' 'romance']
0,m1,1492: conquest of paradise,1992,6.2,10421.0,['adventure' 'biography' 'drama' 'history']
1,m2,15 minutes,2001,6.1,25854.0,['action' 'crime' 'drama' 'thriller']
2,m3,2001: a space odyssey,1968,8.4,163227.0,['adventure' 'mystery' 'sci-fi']
3,m4,48 hrs.,1982,6.9,22289.0,['action' 'comedy' 'crime' 'drama' 'thriller']
4,m5,the fifth element,1997,7.5,133756.0,['action' 'adventure' 'romance' 'sci-fi' 'thri...
...,...,...,...,...,...,...
611,m612,watchmen,2009,7.8,135229.0,['action' 'crime' 'fantasy' 'mystery' 'sci-fi'...
612,m613,xxx,2002,5.6,53505.0,['action' 'adventure' 'crime']
613,m614,x-men,2000,7.4,122149.0,['action' 'sci-fi']
614,m615,young frankenstein,1974,8.0,57618.0,['comedy' 'sci-fi']
615,m616,zulu dawn,1979,6.4,1911.0,['action' 'adventure' 'drama' 'history' 'war']

<br>

# **Import Excel File**

In [18]:
pd.read_excel('data/27_data/ExcelTestData1.xlsx', sheet_name='Sheet1').head()

   MD    DT1 RHOB1
0  ft  us/ft  g/cc
1  50    200     2
2  60    200     2
3  70    200     2
4  80    200     2

In [19]:
pd.read_excel('data/27_data/ExcelTestData1.xlsx', sheet_name='Sheet2').head()

       MD  INC. AZM.
0      ft   deg  deg
1       0     0  200
2  166.67  0.04  200
3  333.33  0.09  200
4     500  0.13  200

<br>

# **Import Json file**

In [20]:
pd.read_json('data/27_data/train.json')

          id      cuisine                                        ingredients
0      10259        greek  [romaine lettuce, black olives, grape tomatoes...
1      25693  southern_us  [plain flour, ground pepper, salt, tomatoes, g...
2      20130     filipino  [eggs, pepper, salt, mayonaise, cooking oil, g...
3      22213       indian                [water, vegetable oil, wheat, salt]
4      13162       indian  [black pepper, shallots, cornflour, cayenne pe...
...      ...          ...                                                ...
39769  29109        irish  [light brown sugar, granulated sugar, butter, ...
39770  11462      italian  [KRAFT Zesty Italian Dressing, purple onion, b...
39771   2238        irish  [eggs, citrus fruit, raisins, sourdough starte...
39772  41882      chinese  [boneless chicken skinless thigh, minced garli...
39773   2362      mexican  [green chile, jalapeno chilies, onions, ground...

[39774 rows x 3 columns]

<br>

# **Import Data from SQL Database**

In [21]:
import mysql.connector
import pandas as pd

In [23]:
con = mysql.connector.connect(host='localhost',user='root',password='',database='import_practice')

In [24]:
df = pd.read_sql_query('select * from invoices', con)

C:\Users\HP\AppData\Local\Temp\ipykernel_25692\523292886.py:1: UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.
  df = pd.read_sql_query('select * from invoices', con)

<br>

# **Exporting Data**

### **Export CSV**

In [25]:
pd.read_sql_query('select * from invoices', con).to_csv('data/27_data/invoices.csv', index=False)

C:\Users\HP\AppData\Local\Temp\ipykernel_25692\1577424634.py:1: UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.
  pd.read_sql_query('select * from invoices', con).to_csv('data/27_data/invoices.csv', index=False)

<br>

# **Export Json**

In [26]:
df.to_json('data/27_data/invoicesj.json', index=False)

<br>

# **Export Html**

In [27]:
df.to_html('data/27_data/invoicesh.html')

<br>

# **Export Excel**

In [28]:
df.to_excel('data/27_data/invoices.xlsx', index=False)

In [29]:
a = df["Order Id"]
b = df["Date"]

In [30]:
# Multiple sheets

with pd.ExcelWriter('data/27_data/multipl.xlsx') as writer:
    a.to_excel(writer, sheet_name='one')
    b.to_excel(writer, sheet_name='two')

<br>

# **Export SQL**

In [31]:
import pymysql
from sqlalchemy import create_engine

In [32]:
engine = create_engine("mysql+pymysql://root:@localhost/import_practice")

In [33]:
df.to_sql('inovices', con=engine, if_exists='append')

50017

<br>

# **Fetching Data from API**

In [63]:
import requests

API_KEY = "AIzaSyD__Mcuj---PUqevfXjzubeuwycQCTqz8k"

url = "https://www.googleapis.com/youtube/v3/search"

params = {
    "part": "snippet",
    "q": "Python tutorial",
    "type": "video",
    "maxResults": 1000000000,
    "key": API_KEY
}

response = requests.get(url, params=params)

print(response.status_code)

200

In [64]:
response.json()

{'kind': 'youtube#searchListResponse',
 'etag': 'rZzEP7tzUfy6z7ikNW58OWcGIws',
 'nextPageToken': 'CDIQAA',
 'regionCode': 'PK',
 'pageInfo': {'totalResults': 1000000, 'resultsPerPage': 50},
 'items': [{'kind': 'youtube#searchResult',
   'etag': 'OXkkntFB5219bicVgCzX6wCML8w',
   'id': {'kind': 'youtube#video', 'videoId': 'q3AuP01daL4'},
   'snippet': {'publishedAt': '2026-07-29T17:41:12Z',
    'channelId': 'UCBwmMxybNva6P_5VmxjzwqA',
    'title': 'Python Full Course for Beginners',
    'description': 'Get Placement Ready & learn from the best No.1 Online Tech Placement Batches : https://linktr.ee/apnacollege.in Python Notes ...',
    'thumbnails': {'default': {'url': 'https://i.ytimg.com/vi/q3AuP01daL4/default.jpg',
      'width': 120,
      'height': 90},
     'medium': {'url': 'https://i.ytimg.com/vi/q3AuP01daL4/mqdefault.jpg',
      'width': 320,
      'height': 180},
     'high': {'url': 'https://i.ytimg.com/vi/q3AuP01daL4/hqdefault.jpg',
      'width': 480,
      'height': 360}},
    'channelTitle': 'Apna College',
    'liveBroadcastContent': 'none',
    'publishTime': '2026-07-29T17:41:12Z'}},
  {'kind': 'youtube#searchResult',
   'etag': 'jctXvOMUNwx8eshGP7bgX4uolsw',
   'id': {'kind': 'youtube#video', 'videoId': 'kqtD5dpn9C8'},
   'snippet': {'publishedAt': '2020-09-16T13:00:20Z',
    'channelId': 'UCWv7vMbMWH4-V0ZXdmDpPBA',
    'title': 'Python for Beginners - Learn Coding with Python in 1 Hour',
    'description': 'Learn Python basics in just 1 hour! Perfect for beginners interested in AI and coding. ⚡ Plus, get 6 months of PyCharm FREE with ...',
    'thumbnails': {'default': {'url': 'https://i.ytimg.com/vi/kqtD5dpn9C8/default.jpg',
      'width': 120,
      'height': 90},
     'medium': {'url': 'https://i.ytimg.com/vi/kqtD5dpn9C8/mqdefault.jpg',
      'width': 320,
      'height': 180},
     'high': {'url': 'https://i.ytimg.com/vi/kqtD5dpn9C8/hqdefault.jpg',
      'width': 480,
      'height': 360}},
    'channelTitle': 'Programming with Mosh',
    'liveBroadcastContent': 'none',
    'publishTime': '2020-09-16T13:00:20Z'}},
  {'kind': 'youtube#searchResult',
   'etag': '5OFwqtaXPjpHnpWQcuA1F70-4zg',
   'id': {'kind': 'youtube#video', 'videoId': 't2_Q2BRzeEE'},
   'snippet': {'publishedAt': '2024-01-26T15:31:21Z',
    'channelId': 'UC1XBh-m27kkgwLAwu_SRJBg',
    'title': 'Python Full Course❤️ | Variables &amp; Data Types | Lecture 1',
    'description': 'This lecture was made with a lot of love❤️ Download Notes : https://dsa.apnacollege.in/studymaterial/python ✨ Instagram ...',
    'thumbnails': {'default': {'url': 'https://i.ytimg.com/vi/t2_Q2BRzeEE/default.jpg',
      'width': 120,
      'height': 90},
     'medium': {'url': 'https://i.ytimg.com/vi/t2_Q2BRzeEE/mqdefault.jpg',
      'width': 320,
      'height': 180},
     'high': {'url': 'https://i.ytimg.com/vi/t2_Q2BRzeEE/hqdefault.jpg',
      'width': 480,
      'height': 360}},
    'channelTitle': 'Shradha Khapra',
    'liveBroadcastContent': 'none',
    'publishTime': '2024-01-26T15:31:21Z'}},
  {'kind': 'youtube#searchResult',
   'etag': 'dZzFUQfjpLNSEGZrVODhcaeOT_M',
   'id': {'kind': 'youtube#video', 'videoId': 'XV-lIaO00H8'},
   'snippet': {'publishedAt': '2026-03-04T16:56:26Z',
    'channelId': 'UCBwmMxybNva6P_5VmxjzwqA',
    'title': 'Complete Python Learning RoadMap (A to Z)',
    'description': 'How to start learning Python Language ? How to learn Python Faster & resources for learning. Python Playlist (complete) ...',
    'thumbnails': {'default': {'url': 'https://i.ytimg.com/vi/XV-lIaO00H8/default.jpg',
      'width': 120,
      'height': 90},
     'medium': {'url': 'https://i.ytimg.com/vi/XV-lIaO00H8/mqdefault.jpg',
      'width': 320,
      'height': 180},
     'high': {'url': 'https://i.ytimg.com/vi/XV-lIaO00H8/hqdefault.jpg',
      'width': 480,
      'height': 360}},
    'channelTitle': 'Apna College',
    'liveBroadcastContent': 'none',
    'publishTime': '2026-03-04T16:56:26Z'}},
  {'kind': 'youtube#searchResult',
   'etag': '6W3UFrjtJ5T33L70kNDCCaattOE',
   'id': {'kind': 'youtube#video', 'videoId': 'fr1f84rg4Nw'},
   'snippet': {'publishedAt': '2018-10-11T14:26:32Z',
    'channelId': 'UCeVMnSShP_Iviwkknt83cww',
    'title': '15 Minute Python Tutorial For Beginners In Hindi (Full &amp; Complete Python Crash Course)',
    'description': 'Python Udemy Course: https://goharry.in/python Get this course at 90% Discount if you use this link Source Code ...',
    'thumbnails': {'default': {'url': 'https://i.ytimg.com/vi/fr1f84rg4Nw/default.jpg',
      'width': 120,
      'height': 90},
     'medium': {'url': 'https://i.ytimg.com/vi/fr1f84rg4Nw/mqdefault.jpg',
      'width': 320,
      'height': 180},
     'high': {'url': 'https://i.ytimg.com/vi/fr1f84rg4Nw/hqdefault.jpg',
      'width': 480,
      'height': 360}},
    'channelTitle': 'CodeWithHarry',
    'liveBroadcastContent': 'none',
    'publishTime': '2018-10-11T14:26:32Z'}},
  {'kind': 'youtube#searchResult',
   'etag': '-nt_8kTfq6vFldpRJZR_GTq5ypU',
   'id': {'kind': 'youtube#video', 'videoId': '7wnove7K-ZQ'},
   'snippet': {'publishedAt': '2022-11-28T11:30:03Z',
    'channelId': 'UCeVMnSShP_Iviwkknt83cww',
    'title': 'Introduction to Programming &amp; Python | Python Tutorial - Day #1',
    'description': 'Python Udemy Course: https://goharry.in/python Get this course at 90% Discount if you use this link Code Backup Repository: ...',
    'thumbnails': {'default': {'url': 'https://i.ytimg.com/vi/7wnove7K-ZQ/default.jpg',
      'width': 120,
      'height': 90},
     'medium': {'url': 'https://i.ytimg.com/vi/7wnove7K-ZQ/mqdefault.jpg',
      'width': 320,
      'height': 180},
     'high': {'url': 'https://i.ytimg.com/vi/7wnove7K-ZQ/hqdefault.jpg',
      'width': 480,
      'height': 360}},
    'channelTitle': 'CodeWithHarry',
    'liveBroadcastContent': 'none',
    'publishTime': '2022-11-28T11:30:03Z'}},
  {'kind': 'youtube#searchResult',
   'etag': 'M67RHFWxpccwLFbRU_iAX4vXOME',
   'id': {'kind': 'youtube#video', 'videoId': 'XIR20HH8mNY'},
   'snippet': {'publishedAt': '2022-09-03T05:12:28Z',
    'channelId': 'UCJihyK0A38SZ6SdJirEdIOw',
    'title': 'Lec-1: What is Python? Introduction to Python 🐍 | Why Python | Where Python is used..',
    'description': 'Python is a popular programming language. It was created by Guido van Rossum, and released in 1991 at CWI(Centrum ...',
    'thumbnails': {'default': {'url': 'https://i.ytimg.com/vi/XIR20HH8mNY/default.jpg',
      'width': 120,
      'height': 90},
     'medium': {'url': 'https://i.ytimg.com/vi/XIR20HH8mNY/mqdefault.jpg',
      'width': 320,
      'height': 180},
     'high': {'url': 'https://i.ytimg.com/vi/XIR20HH8mNY/hqdefault.jpg',
      'width': 480,
      'height': 360}},
    'channelTitle': 'Gate Smashers',
    'liveBroadcastContent': 'none',
    'publishTime': '2022-09-03T05:12:28Z'}},
  {'kind': 'youtube#searchResult',
   'etag': '1km9zQYJ6KglxXg0ab_6TvW9C_Q',
   'id': {'kind': 'youtube#video', 'videoId': 'K5KVEU3aaeQ'},
   'snippet': {'publishedAt': '2025-02-12T12:30:31Z',
    'channelId': 'UCWv7vMbMWH4-V0ZXdmDpPBA',
    'title': 'Python Full Course for Beginners',
    'description': 'Master Python from scratch No fluff—just clear, practical coding skills to kickstart your journey! Want to dive deeper? - Check ...',
    'thumbnails': {'default': {'url': 'https://i.ytimg.com/vi/K5KVEU3aaeQ/default.jpg',
      'width': 120,
      'height': 90},
     'medium': {'url': 'https://i.ytimg.com/vi/K5KVEU3aaeQ/mqdefault.jpg',
      'width': 320,
      'height': 180},
     'high': {'url': 'https://i.ytimg.com/vi/K5KVEU3aaeQ/hqdefault.jpg',
      'width': 480,
      'height': 360}},
    'channelTitle': 'Programming with Mosh',
    'liveBroadcastContent': 'none',
    'publishTime': '2025-02-12T12:30:31Z'}},
  {'kind': 'youtube#searchResult',
   'etag': '_tS9me-1lpv4Paz-vG9Fr2h_zK8',
   'id': {'kind': 'youtube#video', 'videoId': 'Ro_MScTDfU4'},
   'snippet': {'publishedAt': '2024-11-18T14:00:24Z',
    'channelId': 'UCuudpdbKmQWq2PPzYgVCWlA',
    'title': 'Learn Python in Only 30 Minutes (Beginner Tutorial)',
    'description': "In this video I'm going to be teaching you the core concepts that you need to know to get started with using Python. ▷ Become ...",
    'thumbnails': {'default': {'url': 'https://i.ytimg.com/vi/Ro_MScTDfU4/default.jpg',
      'width': 120,
      'height': 90},
     'medium': {'url': 'https://i.ytimg.com/vi/Ro_MScTDfU4/mqdefault.jpg',
      'width': 320,
      'height': 180},
     'high': {'url': 'https://i.ytimg.com/vi/Ro_MScTDfU4/hqdefault.jpg',
      'width': 480,
      'height': 360}},
    'channelTitle': 'Indently',
    'liveBroadcastContent': 'none',
    'publishTime': '2024-11-18T14:00:24Z'}},
  {'kind': 'youtube#searchResult',
   'etag': 'Bjf-w2pzPwuuGj6RzJTHv4cW6vY',
   'id': {'kind': 'youtube#video', 'videoId': 'mC4nyib2sfg'},
   'snippet': {'publishedAt': '2025-11-19T22:01:02Z',
    'channelId': 'UC7zZ2-Q_oxbUaoMVL0z51wg',
    'title': 'How I Would Learn Python FAST (if I could start over)',
    'description': "If I had to learn Python again from scratch.. and learn it FAST - this is exactly how I'd do it. After teaching myself Python in just two ...",
    'thumbnails': {'default': {'url': 'https://i.ytimg.com/vi/mC4nyib2sfg/default.jpg',
      'width': 120,
      'height': 90},
     'medium': {'url': 'https://i.ytimg.com/vi/mC4nyib2sfg/mqdefault.jpg',
      'width': 320,
      'height': 180},
     'high': {'url': 'https://i.ytimg.com/vi/mC4nyib2sfg/hqdefault.jpg',
      'width': 480,
      'height': 360}},
    'channelTitle': 'Sajjaad Khader',
    'liveBroadcastContent': 'none',
    'publishTime': '2025-11-19T22:01:02Z'}},
  {'kind': 'youtube#searchResult',
   'etag': 'gD2UFQyJsxhoty5V5FSKguvP6Ck',
   'id': {'kind': 'youtube#video', 'videoId': 'nluUYtejoIE'},
   'snippet': {'publishedAt': '2024-06-21T07:55:33Z',
    'channelId': 'UCAy1PN6jrZXrGFg79WP_91A',
    'title': 'Python Basics: Your FIRST Program in Under a Minute! 🚀',
    'description': 'In this quick tutorial, I\'ll show you how to write your very first line of Python code: the classic "Hello, World!" ✨ Whether you\'re a ...',
    'thumbnails': {'default': {'url': 'https://i.ytimg.com/vi/nluUYtejoIE/default.jpg',
      'width': 120,
      'height': 90},
     'medium': {'url': 'https://i.ytimg.com/vi/nluUYtejoIE/mqdefault.jpg',
      'width': 320,
      'height': 180},
     'high': {'url': 'https://i.ytimg.com/vi/nluUYtejoIE/hqdefault.jpg',
      'width': 480,
      'height': 360}},
    'channelTitle': 'The Programmers Realm',
    'liveBroadcastContent': 'none',
    'publishTime': '2024-06-21T07:55:33Z'}},
  {'kind': 'youtube#searchResult',
   'etag': '-nsN_PU5UNkvF-UuUUSvvgfLdkw',
   'id': {'kind': 'youtube#video', 'videoId': 'UrsmFxEIp5k'},
   'snippet': {'publishedAt': '2024-06-16T05:36:24Z',
    'channelId': 'UCeVMnSShP_Iviwkknt83cww',
    'title': 'Python Tutorial For Beginners in Hindi | Complete Python Course 🔥',
    'description': "Exciting News! I've just launched my Data Science Course – and it's now in Early Bird Access! If you loved this Python course, ...",
    'thumbnails': {'default': {'url': 'https://i.ytimg.com/vi/UrsmFxEIp5k/default.jpg',
      'width': 120,
      'height': 90},
     'medium': {'url': 'https://i.ytimg.com/vi/UrsmFxEIp5k/mqdefault.jpg',
      'width': 320,
      'height': 180},
     'high': {'url': 'https://i.ytimg.com/vi/UrsmFxEIp5k/hqdefault.jpg',
      'width': 480,
      'height': 360}},
    'channelTitle': 'CodeWithHarry',
    'liveBroadcastContent': 'none',
    'publishTime': '2024-06-16T05:36:24Z'}},
  {'kind': 'youtube#searchResult',
   'etag': 'pQ345NgnqBSMAnNt3oHOsBph-2Q',
   'id': {'kind': 'youtube#video', 'videoId': 'xkZMUX_oQX4'},
   'snippet': {'publishedAt': '2024-05-28T06:00:22Z',
    'channelId': 'UCv9bWHC0DIn-Xb7ALNoOGWQ',
    'title': 'Python - Introduction - W3Schools.com',
    'description': 'This video is an introduction Python. Part of a series of video tutorials to learn Python for beginners! The page this is based on: ...',
    'thumbnails': {'default': {'url': 'https://i.ytimg.com/vi/xkZMUX_oQX4/default.jpg',
      'width': 120,
      'height': 90},
     'medium': {'url': 'https://i.ytimg.com/vi/xkZMUX_oQX4/mqdefault.jpg',
      'width': 320,
      'height': 180},
     'high': {'url': 'https://i.ytimg.com/vi/xkZMUX_oQX4/hqdefault.jpg',
      'width': 480,
      'height': 360}},
    'channelTitle': 'w3schools.com',
    'liveBroadcastContent': 'none',
    'publishTime': '2024-05-28T06:00:22Z'}},
  {'kind': 'youtube#searchResult',
   'etag': 'I_rlcUmBoHxZk5fXbvvCvJi1MSs',
   'id': {'kind': 'youtube#video', 'videoId': '_uQrJ0TkZlc'},
   'snippet': {'publishedAt': '2019-02-18T15:00:08Z',
    'channelId': 'UCWv7vMbMWH4-V0ZXdmDpPBA',
    'title': 'Python Full Course for Beginners',
    'description': 'Learn Python for AI, machine learning, and web development with this beginner-friendly course! Get 6 months of PyCharm ...',
    'thumbnails': {'default': {'url': 'https://i.ytimg.com/vi/_uQrJ0TkZlc/default.jpg',
      'width': 120,
      'height': 90},
     'medium': {'url': 'https://i.ytimg.com/vi/_uQrJ0TkZlc/mqdefault.jpg',
      'width': 320,
      'height': 180},
     'high': {'url': 'https://i.ytimg.com/vi/_uQrJ0TkZlc/hqdefault.jpg',
      'width': 480,
      'height': 360}},
    'channelTitle': 'Programming with Mosh',
    'liveBroadcastContent': 'none',
    'publishTime': '2019-02-18T15:00:08Z'}},
  {'kind': 'youtube#searchResult',
   'etag': 'b6GbOGPjbPW5NO4iisukhZy98eE',
   'id': {'kind': 'youtube#video', 'videoId': 'g4Ffdh41vRQ'},
   'snippet': {'publishedAt': '2025-05-09T12:51:50Z',
    'channelId': 'UCeVMnSShP_Iviwkknt83cww',
    'title': 'Complete Python Programming Roadmap (Zero to Expert) 🐍',
    'description': 'Python Udemy Course: https://goharry.in/python If you are looking to learn Python from an absolute beginner, this is the best and ...',
    'thumbnails': {'default': {'url': 'https://i.ytimg.com/vi/g4Ffdh41vRQ/default.jpg',
      'width': 120,
      'height': 90},
     'medium': {'url': 'https://i.ytimg.com/vi/g4Ffdh41vRQ/mqdefault.jpg',
      'width': 320,
      'height': 180},
     'high': {'url': 'https://i.ytimg.com/vi/g4Ffdh41vRQ/hqdefault.jpg',
      'width': 480,
      'height': 360}},
    'channelTitle': 'CodeWithHarry',
    'liveBroadcastContent': 'none',
    'publishTime': '2025-05-09T12:51:50Z'}},
  {'kind': 'youtube#searchResult',
   'etag': 'hIh4VzhAN15AuVcWv-FQz52rk7s',
   'id': {'kind': 'youtube#video', 'videoId': 'q2-pnQffZik'},
   'snippet': {'publishedAt': '2024-12-31T02:30:33Z',
    'channelId': 'UC7zZ2-Q_oxbUaoMVL0z51wg',
    'title': 'Learn Python for FREE in 2025',
    'description': 'Learn Python for FREE in 2025 #coding #compsci #python #fyp Source: TikTok (individualkex)',
    'thumbnails': {'default': {'url': 'https://i.ytimg.com/vi/q2-pnQffZik/default.jpg',
      'width': 120,
      'height': 90},
     'medium': {'url': 'https://i.ytimg.com/vi/q2-pnQffZik/mqdefault.jpg',
      'width': 320,
      'height': 180},
     'high': {'url': 'https://i.ytimg.com/vi/q2-pnQffZik/hqdefault.jpg',
      'width': 480,
      'height': 360}},
    'channelTitle': 'Sajjaad Khader',
    'liveBroadcastContent': 'none',
    'publishTime': '2024-12-31T02:30:33Z'}},
  {'kind': 'youtube#searchResult',
   'etag': '2l_8dBOgw2RXICSg9FUxPTYonI4',
   'id': {'kind': 'youtube#video', 'videoId': '6GuyMZ-cSzE'},
   'snippet': {'publishedAt': '2026-07-01T13:47:41Z',
    'channelId': 'UCh9nVJoWXmFb7sLApWGcLPQ',
    'title': 'Python Tutorial for AI: Everything You Need in 2 Hours',
    'description': 'This Python mini-course is built by keeping in mind the use case of AI. Any AI aspirant who wants to learn AI using Python or want ...',
    'thumbnails': {'default': {'url': 'https://i.ytimg.com/vi/6GuyMZ-cSzE/default.jpg',
      'width': 120,
      'height': 90},
     'medium': {'url': 'https://i.ytimg.com/vi/6GuyMZ-cSzE/mqdefault.jpg',
      'width': 320,
      'height': 180},
     'high': {'url': 'https://i.ytimg.com/vi/6GuyMZ-cSzE/hqdefault.jpg',
      'width': 480,
      'height': 360}},
    'channelTitle': 'codebasics',
    'liveBroadcastContent': 'none',
    'publishTime': '2026-07-01T13:47:41Z'}},
  {'kind': 'youtube#searchResult',
   'etag': 'sft0O8daguSzigE5C4o_LppZlxs',
   'id': {'kind': 'youtube#video', 'videoId': 'xAcTmDO6NTI'},
   'snippet': {'publishedAt': '2024-04-11T14:01:57Z',
    'channelId': 'UCEBb1b_L6zDS3xTUrIALZOw',
    'title': 'Lecture 1: Introduction to CS and Programming Using Python',
    'description': 'MIT 6.100L Introduction to CS and Programming using Python, Fall 2022 Instructor: Ana Bell View the complete course: ...',
    'thumbnails': {'default': {'url': 'https://i.ytimg.com/vi/xAcTmDO6NTI/default.jpg',
      'width': 120,
      'height': 90},
     'medium': {'url': 'https://i.ytimg.com/vi/xAcTmDO6NTI/mqdefault.jpg',
      'width': 320,
      'height': 180},
     'high': {'url': 'https://i.ytimg.com/vi/xAcTmDO6NTI/hqdefault.jpg',
      'width': 480,
      'height': 360}},
    'channelTitle': 'MIT OpenCourseWare',
    'liveBroadcastContent': 'none',
    'publishTime': '2024-04-11T14:01:57Z'}},
  {'kind': 'youtube#searchResult',
   'etag': 'iHpYbseidi1IBEvVi2tUOjWzVRk',
   'id': {'kind': 'youtube#video', 'videoId': 'fWjsdhR3z3c'},
   'snippet': {'publishedAt': '2021-05-26T12:32:40Z',
    'channelId': 'UCuudpdbKmQWq2PPzYgVCWlA',
    'title': 'Learn Python in Less than 10 Minutes for Beginners (Fast &amp; Easy)',
    'description': "In this crash course I'll be teaching you the basics of Python in less than 10 minutes. Python is super easy to learn compared to ...",
    'thumbnails': {'default': {'url': 'https://i.ytimg.com/vi/fWjsdhR3z3c/default.jpg',
      'width': 120,
      'height': 90},
     'medium': {'url': 'https://i.ytimg.com/vi/fWjsdhR3z3c/mqdefault.jpg',
      'width': 320,
      'height': 180},
     'high': {'url': 'https://i.ytimg.com/vi/fWjsdhR3z3c/hqdefault.jpg',
      'width': 480,
      'height': 360}},
    'channelTitle': 'Indently',
    'liveBroadcastContent': 'none',
    'publishTime': '2021-05-26T12:32:40Z'}},
  {'kind': 'youtube#searchResult',
   'etag': 'VE5KHhP0k5kT9wtr4pjy005syWc',
   'id': {'kind': 'youtube#video', 'videoId': 'IfKlGhRc7Dc'},
   'snippet': {'publishedAt': '2024-06-16T06:40:42Z',
    'channelId': 'UCOgJpLSS48Hzemjv-d-ihYQ',
    'title': 'Python Roadmap for Beginners! 🐍 Learn Python Programming Step-by-Step&quot; #python #conding',
    'description': 'Python Roadmap for Beginners! Learn Python Programming Step-by-Step" @MissionAdda4 #codingtutorial #pythonroadmap ...',
    'thumbnails': {'default': {'url': 'https://i.ytimg.com/vi/IfKlGhRc7Dc/default.jpg',
      'width': 120,
      'height': 90},
     'medium': {'url': 'https://i.ytimg.com/vi/IfKlGhRc7Dc/mqdefault.jpg',
      'width': 320,
      'height': 180},
     'high': {'url': 'https://i.ytimg.com/vi/IfKlGhRc7Dc/hqdefault.jpg',
      'width': 480,
      'height': 360}},
    'channelTitle': 'Mission Adda',
    'liveBroadcastContent': 'none',
    'publishTime': '2024-06-16T06:40:42Z'}},
  {'kind': 'youtube#searchResult',
   'etag': 'fOZh60QjKFa63fNTq8MJIlpk6VA',
   'id': {'kind': 'youtube#video', 'videoId': 'qxRt-cS7XzU'},
   'snippet': {'publishedAt': '2025-03-18T08:36:20Z',
    'channelId': 'UCedPzKBFt6W61gtfKp5tdzA',
    'title': 'How to Install Python 3.13.1 on Windows 11 (2025)',
    'description': "How to Install Python on Windows 11 | Step-by-Step Guide* Welcome to our channel! In this video, we'll guide you through the ...",
    'thumbnails': {'default': {'url': 'https://i.ytimg.com/vi/qxRt-cS7XzU/default.jpg',
      'width': 120,
      'height': 90},
     'medium': {'url': 'https://i.ytimg.com/vi/qxRt-cS7XzU/mqdefault.jpg',
      'width': 320,
      'height': 180},
     'high': {'url': 'https://i.ytimg.com/vi/qxRt-cS7XzU/hqdefault.jpg',
      'width': 480,
      'height': 360}},
    'channelTitle': 'Singh Edits Pro',
    'liveBroadcastContent': 'none',
    'publishTime': '2025-03-18T08:36:20Z'}},
  {'kind': 'youtube#searchResult',

In [65]:
li = []

for i in response.json()["items"]:
    dic = {
        'title':i['snippet']['title'],
        'publishedtime':i['snippet']['publishTime'],
        'description':i['snippet']['description'],
        'chanelname':i['snippet']['channelTitle']  
    }
    li.append(dic)

In [80]:
df = pd.DataFrame(li)

In [82]:
df["publishedtime"]=pd.to_datetime(df["publishedtime"])

In [ ]:
# This is the latest video on python programing language

df.nlargest(1, 'publishedtime')

,title,publishedtime,description,chanelname
0,Python Full Course for Beginners,2026-07-29 17:41:12+00:00,Get Placement Ready & learn from the best No.1...,Apna College

<br>

<br>

# **Web Scarpping**

In [87]:
import pandas as pd
import requests
from bs4 import BeautifulSoup
import numpy as np

### **if response code is 403**
 - headers={'User-Agent':'Mozilla/5.0 (Windows NT 6.3; Win 64 ; x64) Apple WeKit /537.36(KHTML , like Gecko) Chrome/80.0.3987.162 Safari/537.36'}
 -requests.get('url',headers=headers).text

In [85]:
webpage=requests.get('https://www.ambitionbox.com/list-of-companies?page=1').text

In [88]:
soup=BeautifulSoup(webpage,'lxml')

In [ ]:
#print(soup.prettify())

In [ ]:
soup.find_all('h1')[0].text

'List of companies in India'

### **TO FIND OUT NAMES OF THE COMPANIES**

In [ ]:
for i in soup.find_all('h2'):
  print(i.text.strip())

TCS
Accenture
ICICI Bank
Cognizant
HDFC Bank
Capgemini
Tech Mahindra
HCL Technologies
L&T
Infosys
Tata Motors
IBM
Genpact
Reliance jio
Axis Bank
Wipro
Concentrix Corporation
HDB Financial Services
Vodafone
Bharti Airtel
Kotak Mahindra Bank
Amazon
Reliance
Bajaj Finserv
IndusInd Bank
Indian Army
Teleperformance
Hinduja Global Solutions
Samsung
Mahindra & Mahindra

In [ ]:
for i in soup.find_all('p'):
  print(i.text.strip())

Company Overview
477,887 unique
			companies found
Sort By:
Popular
3.9
Public
Mumbai + 164 more
52 years old
10000+ employees
Tata Consultancy Services is an IT services, consulting and business solutions organisation that has been partnering with the world’s largest businesses in their transformation journeys for the last 50 years.

A part of the Tata group, India's largest multinational business group, TCS has over 436,000 of the world’s best-trained consultants in 46 countries. The company is listed on the BSE (formerly Bombay Stock Exchange) and the NSE (National Stock Exchange) in India.

TCS'​ proactive stance on climate change and award winning work with communities across the world have earned it a place in leading sustainability indices such as the Dow Jones Sustainability Index (DJSI), MSCI Global Sustainability Index and the FTSE4Good Emerging Index.
4.0
Private
Dublin + 98 more
31 years old
10000+ employees
Accenture is a leading global professional services company, providing a broad range of services and solutions in strategy, consulting, digital, technology and operations. Combining unmatched experience and specialized skills across more than 40 industries and all business functions – underpinned by the world’s largest delivery network – Accenture works at the intersection of business and technology to help clients improve their performance and create sustainable value for their stakeholders. With 449,000 people serving clients in more than 120 countries, Accenture drives innovation to improve the way the world works and lives. Visit us at www.accenture.com.
4.1
Public
Mumbai + 743 more
26 years old
10000+ employees
ICICI Bank is India's largest private sector bank with total consolidated assets of Rs. 11,242.81 billion (US$ 172.5 billion) at March 31, 2018 and profit after tax of Rs. 67.77 billion (US$ 1.0 billion) for the year ended March 31, 2018.

ICICI Bank currently has a network of 4,867 Branches and 14,367 ATMs across India.

ICICI Bank offers a wide range of banking products and financial services to corporate and retail customers through a variety of delivery channels and through its specialised subsidiaries in the areas of investment banking, life and non-life insurance, venture capital and asset management.
3.9
Private
Teaneck + 46 more
26 years old
10000+ employees
Cognizant (NASDAQ-100: CTSH) is one of the world’s leading professional services companies,
transforming clients’ business, operating and technology models for the digital era. Our unique industry-based, consultative approach helps many of the best-known organizations in every industry and geography envision, build and run more innovative and efficient businesses.
Founded in 1994 as a technology development arm of The Dun & Bradstreet Corporation, we were spun off as an independent company in 1996, and have worked closely with large organizations to help them build stronger businesses ever since. Today, Cognizant specializes in helping some of the world’s most established companies to stay the most loved brands in today’s fast-changing technology landscape by advancing every aspect of how they serve their customers: digitizing their products, services and customer experiences; automating their business processes; and modernizing their technology infrastructures
4.0
Public
Mumbai + 729 more
26 years old
10000+ employees
HDFC Bank is one of India’s leading private banks and was among the first to receive approval from the Reserve Bank of India (RBI) to set up a private sector bank in 1994.

Today, HDFC Bank has a banking network of 5,314 branches and 13,640  ATMs spread across 2,768 cities and towns.

HDFC Bank offers a diverse range of financial products and banking services to customers through a growing branch and ATM network and digital channels such as Netbanking, Phonebanking and MobileBanking.
3.4
Private
Paris + 45 more
53 years old
10000+ employees
Capgemini is a global leader in consulting, digital transformation, technology and engineering services. The Group is at the forefront of innovation to address the entire breadth of clients’ opportunities in the evolving world of cloud, digital and platforms. Building on its strong 50-year+ heritage and deep industry-specific expertise, Capgemini enables organizations to realize their business ambitions through an array of services from strategy to operations. Capgemini is driven by the conviction that the business value of technology comes from and through people. Today, it is a multicultural company of 270,000 team members in almost 50 countries. With Altran, the Group reported 2019 combined revenues of €17billion.

Visit us at www.capgemini.com. People matter, results count.
3.6
Public
Pune + 160 more
34 years old
10000+ employees
Tech Mahindra represents the connected world, offering innovative and customer-centric information technology experiences, enabling Enterprises, Associates and the Society to Rise™. We are a USD 4.9 billion company with 125,700+ professionals across 90 countries, helping 941 global customers including Fortune 500 companies. Our convergent, digital, design experiences, innovation platforms and reusable assets connect across a number of technologies to deliver tangible business value and experiences to our stakeholders. Tech Mahindra is the highest ranked Non-U.S. company in the Forbes Global Digital 100 list (2018) and in the Forbes Fab 50 companies in Asia (2018).
3.7
Public
Noida + 111 more
14 years old
10000+ employees
HCL Learning, a wholly owned subsidiary of HCL Infosystems, offers education and training content to schools, colleges, individuals and enterprises. Flagship product DigiSchool is a classroom learning solution with interactive content for K-12. Provides customized content repository that caters to the students’ learning needs. Content is designed and developed by HCL Learning Development Centre, certified by Department of Scientific and Industrial Research.  Also offers vocational trainings in the field of IT and ITES. As of June 2015, claims to be catering to 3,500 schools and 3.5M+ students.
4.2
Public
Mumbai + 337 more
82 years old
10000+ employees
Larsen & Toubro is a major technology, engineering, construction, manufacturing and financial services conglomerate, with global operations. L&T addresses critical needs in key sectors - Hydrocarbon, Infrastructure, Power, Process Industries and Defence - for customers in over 30 countries around the world.

L&T is engaged in core, high impact sectors of the economy and our integrated capabilities span the entire spectrum of ‘design to deliver’. With 8 decades of a strong, customer focused approach and a continuous quest for world-class quality, we have unmatched expertise across Technology, Engineering, Construction, Infrastructure Projects and Manufacturing, and maintain a leadership in all our major lines of business.

Every aspect of L&T's businesses is characterised by professionalism and high standards of corporate governance. Sustainability is embedded into our long-term strategy for growth.
3.9
Public
Bangalore + 68 more
39 years old
10000+ employees
Infosys is a global leader in next-generation digital services and consulting. We enable clients in 45 countries to navigate their digital transformation. With over three decades of experience in managing the systems and workings of global enterprises, we expertly steer our clients through the many nexts of their digital journey. We do it by enabling the enterprise with an AI-powered core that helps prioritize the execution of change. We also empower the business with agile digital at scale to deliver unprecedented levels of performance and customer delight. Our always-on learning agenda drives their continuous improvement through building and transferring digital skills, expertise and ideas from our innovation ecosystem.
4.1
Public
Pune + 344 more
75 years old
10000+ employees
Tata Motors Limited, a USD 45 billion organisation, is a leading automobile manufacturer with a portfolio that includes a wide range of cars, utility vehicles, trucks, buses and defence vehicles. Our marque can be found on and off-road in over 175 countries around the globe.

Our focus on connecting aspirations and our pipeline of tech-enabled products keeps us at the forefront of the market. We have identified six key mobility drivers that will lead us into the future – modular architecture, complexity reduction in manufacturing, connected & autonomous vehicles, clean drivelines, shared mobility, and low total cost of ownership. Our sub-brand TAMO is an incubating centre of innovation that will spark new mobility solutions through new technologies, business models and partnerships.
4.1
Private
New York + 73 more
109 years old
10000+ employees
At IBM, work is more than a job - it's a calling: To build. To design. To code. To consult. To think along with clients and sell. To make markets. To invent. To collaborate. Not just to do something better, but to attempt things you've never thought possible. To lead in this new era of technology and solve some of the world's most challenging problems.

IBM is a leading cloud platform and cognitive solutions company. Restlessly reinventing since 1911, we are the largest technology and consulting employer in the world, with more than 350,000 employees serving clients in 170 countries. With Watson, the AI platform for business, powered by data, we are building industry-based solutions to real-world problems. For more than seven decades, IBM Research has defined the future of information technology with more than 3,000 researchers in 12 labs located across six continents.
4.0
Private
New York + 31 more
23 years old
10000+ employees
Genpact (NYSE: G) is a global professional services firm that makes business transformation real. We drive digital-led innovation and digitally-enabled intelligent operations for our clients, guided by our experience running thousands of processes primarily for Global Fortune 500 companies. We think with design, dream in digital, and solve problems with data and analytics. Combining our expertise in end-to-end operations and our AI-based platform, Genpact Cora, we focus on the details – all 87,000+ of us. From New York to New Delhi and more than 25 countries in between, we connect every dot, reimagine every process, and reinvent companies’ ways of working. We know that reimagining each step from start to finish will create better business outcomes. Whatever it is, we’ll be there with you – accelerating digital transformation to create bold, lasting results – because transformation happens here.

Genpact began in 1997 as a business unit within General Electric. In January 2005, Genpact became an independent company to bring our process expertise and unique DNA in Lean management to clients beyond GE, and then in August 2007, we became a publicly-traded company. Bain Capital became Genpact’s largest shareholder in November 2012, with the strategic objective to grow the company further. Since December 31, 2005, we have expanded from 19,000+ employees and annual revenues of US$491.90 million to 87,000+ employees and annual revenues of US$3.00 billion as of December 31, 2018.
4.0
Public
Navi Mumbai + 606 more
10 years old
10000+ employees
Make a new start. A start that will build beautiful relationships, shape millions of ideas. Enable a new way to live, learn, work and play.

At Jio, we build products and services of the future to empower billions of Indians make their dreams a reality.

Jio is about YOU. Join the movement to make India Digital.
4.0
Public
Mumbai + 670 more
27 years old
10000+ employees
Axis Bank is the third largest private sector bank in India. The Bank offers the entire spectrum of financial services to customer segments covering Large and Mid-Corporates, MSME, Agriculture and Retail Businesses.

The Bank has a large footprint of 4,050 domestic branches (including extension counters) with 11,801 ATMs & 4,917 cash recyclers spread across the country as on 31st March, 2019. The overseas operations of the Bank are spread over nine international offices with branches at Singapore, Hong Kong, Dubai (at the DIFC), Colombo and Shanghai; representative offices at Dhaka, Dubai, Abu Dhabi and an overseas subsidiary at London, UK. The international offices focus on corporate lending, trade finance, syndication, investment banking and liability businesses.
3.8
Public
Bangalore + 123 more
75 years old
10000+ employees
Wipro Limited (NYSE: WIT, BSE: 507685, NSE: WIPRO) is a leading global information technology, consulting and business process services company. We harness the power of cognitive computing, hyper-automation, robotics, cloud, analytics and emerging technologies to help our clients adapt to the digital world and make them successful. A company recognized globally for its comprehensive portfolio of services, a strong commitment to sustainability and good corporate citizenship, we have over 160,000 dedicated employees serving clients across six continents. Together, we discover ideas and connect the dots to build a better and a bold new future.
4.0
Public
Fremont + 39 more
37 years old
10000+ employees
Concentrix is a technology-enabled global business services company specializing in customer engagement and improving business performance. We partner with ambitious, progressive executives around the world to future-proof their business and stay ahead of the competition and customer expectations.

It’s all about tapping into sentiment and building an emotional connection that keeps customers and staff fanatical about your brand. That’s where we come in—we create exceptional customer engagement, accelerate digital transformation, and deliver actionable CX insights.

We help you reimagine your business—and get you there faster than you ever thought possible.
4.0
Private
Ahmedabad + 463 more
13 years old
10000+ employees
HDB Financial Services (HDBFS) is a leading Non-Banking Financial Company (NBFC) that caters to the growing needs of an Aspirational India, serving both Individual & Business Clients.

Incorporated in 2007, we are a well-established business with strong capitalization. HDBFS is accredited with CARE AAA & CRISIL AAA ratings for its long-term debt & Bank facilities and an A1+ rating for its short-term debt & commercial papers, making it a strong and reliable financial institution.

HDBFS maintains a strong commitment to ethical conduct. Transparency is ingrained in the structure of our Code of Ethics and our compliance policies to ensure that the highest standards of professional conduct are consistently reinforced and embedded in every corner of the organisation.
4.2
Public
Berkshire + 364 more
38 years old
10000+ employees
Vodafone is a leader in technology communications through mobile, fixed, broadband and TV.
We have extensive experience in connectivity, convergence and the Internet of Things, as well as championing mobile financial services and digital transformation in emerging markets.

Since making the first mobile call in the UK on 1 January 1985, Vodafone has grown into an international business and one of the most valuable brands in the world. We have mobile operations in 24 countries, partner with mobile networks in 42 more, and provide fixed broadband in 19 markets.

As of 30 September 2019, Vodafone Group had approximately 625 million mobile customers, 27 million fixed broadband customers and 22 million TV customers, including all of the customers in Vodafone’s joint ventures and associates.

We’re working hard to build a digital future that works for everyone
4.2
Public
New Delhi + 347 more
25 years old
10000+ employees
Bharti Airtel is a leading alternative provider of telecommunications services in India and among the top ten global carriers offering services in about 20 other countries, particularly in Africa. Through subsidiaries, the company operates three business units: Telemedia Services (broadband and telephone), Enterprise Services, and Mobile Services. The Enterprise Services group aids both long-distance carriers and corporate clients. Bharti Airtel has more than 220 million mainly mobile subscribers. It provides digital television service for 5 million in India. The company is a unit of Bharti Enterprises, a conglomerate with interests in financial services, food, and retail, besides telecom.
3.8
Public
Mumbai + 361 more
17 years old
10000+ employees
In February 2003, Kotak Mahindra Finance Ltd. (KMFL), the Group's flagship company, received banking license from the Reserve Bank of India (RBI), becoming the first non-banking finance company in India to convert into a bank - Kotak Mahindra Bank Ltd.
Effective April 1, 2015, ING Vysya Bank Ltd. merged with Kotak Mahindra Bank Ltd.
The Bank has four Strategic Business Units – Consumer Banking, Corporate Banking, Commercial Banking and Treasury, which cater to retail and corporate customers across urban and rural India.

The Group offers a wide range of financial services that encompass every sphere of life. From commercial banking, to stock broking, mutual funds, life insurance and investment banking, the Group caters to the diverse financial needs of individuals and the corporate sector. The Group has a wide distribution network through branches and franchisees across India, and international offices in London, New York, California, Dubai, Abu Dhabi, Bahrain, Mauritius and Singapore.
4.1
Private
Washington + 182 more
26 years old
10000+ employees
Amazon is guided by four principles: customer obsession rather than competitor focus, passion for invention, commitment to operational excellence, and long-term thinking. We are driven by the excitement of building technologies, inventing products, and providing services that change lives. We embrace new ways of doing things, make decisions quickly, and are not afraid to fail. We have the scope and capabilities of a large company, and the spirit and heart of a small one.

Together, Amazonians research and develop new technologies from Amazon Web Services to Alexa on behalf of our customers: shoppers, sellers, content creators, and developers around the world.
4.2
Public
Mumbai + 216 more
54 years old
10000+ employees
Reliance Industries Limited is a Fortune 500 company and the largest private sector corporation in India.

Our motto “Growth is Life” aptly captures the ever-evolving spirit of Reliance. We have evolved from being a textiles and polyester company to an integrated player across energy, materials, retail, entertainment and digital services. In each of these areas, we are committed to innovation-led, exponential growth. Our vision has pushed us to achieve global leadership in many of our businesses.

Reliance's products and services portfolio touches almost all Indians on a daily basis, across economic and social spectrums. We are now focussed on building platforms that will herald the Fourth Industrial Revolution and will create opportunities and avenues for India and all its citizens to realise their true potential.
4.1
Public
Pune + 478 more
13 years old
10000+ employees
Bajaj Finserv was formed in April 2007 as a result of its demerger from Bajaj Auto Limited to further the Group’s interests in financial services. This demerger enabled Bajaj Finserv to independently run the core businesses of Lending, Protection and savings. Bajaj Finserv Limited is the holding company for the businesses dealing with financial services of the Bajaj Group. It serves millions of customers in the financial services space by providing solutions for asset acquisition through financing, asset protection through general insurance, family protection and income protection in the form of life and health insurance and retirement and savings solutions
3.6
Public
Mumbai + 365 more
26 years old
10000+ employees

In [ ]:
#for in soup.find_all('p'):
  #print(i.text.strip())

### **TO FIND OUT THE RATINGS**

In [ ]:
len(soup.find_all('p',class_='rating'))

30

### **TO FIND OUT THE NUMBER OF REVIEWS**

In [ ]:
len(soup.find_all('a' , class_='review-count'))

30

### **CONSIDERING THE WHOLE CONTAINER**

In [ ]:
company=soup.find_all('div',class_='company-content-wrapper')

In [ ]:
len(company)

30

In [ ]:
name=[]
rating=[]
reviews=[]
ctype=[]
hq=[]
how_old=[]
no_of_employee=[]

for i in company:

  name.append(i.find('h2').text.strip())
  rating.append(i.find('p',class_='rating').text.strip())
  reviews.append(i.find('a' , class_='review-count').text.strip())
  ctype.append(i.find_all('p',class_='infoEntity')[0].text.strip())
  hq.append(i.find_all('p',class_='infoEntity')[1].text.strip())
  how_old.append(i.find_all('p',class_='infoEntity')[2].text.strip())
  no_of_employee.append(i.find_all('p',class_='infoEntity')[3].text.strip())

df=pd.DataFrame({'name':name,
   'rating':rating,
   'reviews':reviews,
   'company_type':ctype,
   'Head_Quarters':hq,
   'Company_Age':how_old,
   'No_of_Employee':no_of_employee,
   })

In [ ]:
name

['TCS',
 'Accenture',
 'ICICI Bank',
 'Cognizant',
 'HDFC Bank',
 'Capgemini',
 'Tech Mahindra',
 'HCL Technologies',
 'L&T',
 'Infosys',
 'Tata Motors',
 'IBM',
 'Genpact',
 'Reliance jio',
 'Axis Bank',
 'Wipro',
 'Concentrix Corporation',
 'HDB Financial Services',
 'Vodafone',
 'Bharti Airtel',
 'Kotak Mahindra Bank',
 'Amazon',
 'Reliance',
 'Bajaj Finserv',
 'IndusInd Bank',
 'Indian Army',
 'Teleperformance',
 'Hinduja Global Solutions',
 'Samsung',
 'Mahindra & Mahindra']

In [ ]:
rating

['3.9',
 '4.0',
 '4.1',
 '3.9',
 '4.0',
 '3.4',
 '3.6',
 '3.7',
 '4.2',
 '3.9',
 '4.1',
 '4.1',
 '4.0',
 '4.0',
 '4.0',
 '3.8',
 '4.0',
 '4.0',
 '4.2',
 '4.2',
 '3.8',
 '4.1',
 '4.2',
 '4.1',
 '3.6',
 '4.7',
 '3.7',
 '3.8',
 '4.2',
 '4.2']

In [ ]:
reviews

['17.1k Reviews',
 '15k Reviews',
 '13.8k Reviews',
 '12.9k Reviews',
 '12k Reviews',
 '10k Reviews',
 '9.8k Reviews',
 '9.2k Reviews',
 '9.1k Reviews',
 '8.7k Reviews',
 '8.6k Reviews',
 '8.5k Reviews',
 '8.3k Reviews',
 '8.3k Reviews',
 '8.3k Reviews',
 '7.3k Reviews',
 '7.3k Reviews',
 '6.2k Reviews',
 '5.7k Reviews',
 '5.7k Reviews',
 '5.7k Reviews',
 '5.6k Reviews',
 '4.8k Reviews',
 '4.1k Reviews',
 '3.9k Reviews',
 '3.9k Reviews',
 '3.8k Reviews',
 '3.8k Reviews',
 '3.6k Reviews',
 '3.6k Reviews']

In [ ]:
ctype

['Public',
 'Private',
 'Public',
 'Private',
 'Public',
 'Private',
 'Public',
 'Public',
 'Public',
 'Public',
 'Public',
 'Private',
 'Private',
 'Public',
 'Public',
 'Public',
 'Public',
 'Private',
 'Public',
 'Public',
 'Public',
 'Private',
 'Public',
 'Public',
 'Public',
 'Govt agency',
 'Private',
 'Public',
 'Private',
 'Public']

In [ ]:
hq

['Mumbai + 164 more',
 'Dublin + 98 more',
 'Mumbai + 743 more',
 'Teaneck + 46 more',
 'Mumbai + 729 more',
 'Paris + 45 more',
 'Pune + 160 more',
 'Noida + 111 more',
 'Mumbai + 337 more',
 'Bangalore + 68 more',
 'Pune + 344 more',
 'New York + 73 more',
 'New York + 31 more',
 'Navi Mumbai + 606 more',
 'Mumbai + 670 more',
 'Bangalore + 123 more',
 'Fremont + 39 more',
 'Ahmedabad + 463 more',
 'Berkshire + 364 more',
 'New Delhi + 347 more',
 'Mumbai + 361 more',
 'Washington + 182 more',
 'Mumbai + 216 more',
 'Pune + 478 more',
 'Mumbai + 365 more',
 'New Delhi + 211 more',
 'Paris + 45 more',
 'Bangalore + 52 more',
 'Seoul + 292 more',
 'Mumbai + 268 more']

In [ ]:
how_old

['52 years old',
 '31 years old',
 '26 years old',
 '26 years old',
 '26 years old',
 '53 years old',
 '34 years old',
 '14 years old',
 '82 years old',
 '39 years old',
 '75 years old',
 '109 years old',
 '23 years old',
 '10 years old',
 '27 years old',
 '75 years old',
 '37 years old',
 '13 years old',
 '38 years old',
 '25 years old',
 '17 years old',
 '26 years old',
 '54 years old',
 '13 years old',
 '26 years old',
 '125 years old',
 '42 years old',
 '20 years old',
 '82 years old',
 '75 years old']

In [ ]:
no_of_employee

['10000+ employees',
 '10000+ employees',
 '10000+ employees',
 '10000+ employees',
 '10000+ employees',
 '10000+ employees',
 '10000+ employees',
 '10000+ employees',
 '10000+ employees',
 '10000+ employees',
 '10000+ employees',
 '10000+ employees',
 '10000+ employees',
 '10000+ employees',
 '10000+ employees',
 '10000+ employees',
 '10000+ employees',
 '10000+ employees',
 '10000+ employees',
 '10000+ employees',
 '10000+ employees',
 '10000+ employees',
 '10000+ employees',
 '10000+ employees',
 '10000+ employees',
 '10000+ employees',
 '10000+ employees',
 '10000+ employees',
 '10000+ employees',
 '10000+ employees']

In [ ]:
df.shape

(30, 7)

### **creating dataframe for all the pages**

In [ ]:
final=pd.DataFrame()
for j in range(1,1001):
  webpage=requests.get('https://www.ambitionbox.com/list-of-companies?page={}'.format(j)).text
  soup=BeautifulSoup(webpage,'lxml')
  company=soup.find_all('div',class_='company-content-wrapper')
  name=[]
  rating=[]
  reviews=[]
  ctype=[]
  hq=[]
  how_old=[]
  no_of_employee=[]

  for i in company:

    try:
       name.append(i.find('h2').text.strip())
    except:
       name.append(np.nan)

    try:
       rating.append(i.find('p',class_='rating').text.strip())
    except:
       rating.append(np.nan)
   
    try:

      reviews.append(i.find('a' , class_='review-count').text.strip())
    except:
      reviews.append(np.nan)

    try:

      ctype.append(i.find_all('p',class_='infoEntity')[0].text.strip())
    except:
      ctype.append(np.nan)
    try:

      hq.append(i.find_all('p',class_='infoEntity')[1].text.strip())
    except:
      hq.append(np.nan)
    
    try:

      how_old.append(i.find_all('p',class_='infoEntity')[2].text.strip())
    except:
      how_old.append(np.nan)
    try:
      no_of_employee.append(i.find_all('p',class_='infoEntity')[3].text.strip())
    except:
      no_of_employee.append(np.nan)
    

  df=pd.DataFrame({'name':name,
    'rating':rating,
    'reviews':reviews,
    'company_type':ctype,
    'Head_Quarters':hq,
    'Company_Age':how_old,
    'No_of_Employee':no_of_employee,
    })
  
  final=final.append(df,ignore_index=True)

In [ ]:
df.sample(5)

                           name rating  ...    Company_Age    No_of_Employee
2               Bank of America    4.3  ...   22 years old  10000+ employees
22               R.R. Donnelley    4.1  ...  156 years old  10000+ employees
11  Mahindra Holidays & Reso...    3.9  ...   24 years old  10000+ employees
23  GVK Emergency Management...    3.9  ...   15 years old  10000+ employees
9            Itc Infotech India    3.4  ...   20 years old  10000+ employees

[5 rows x 7 columns]

In [ ]:
df.shape

(30, 7)

In [ ]:
final.shape

(30000, 7)

<br>

----