<b><h1><center>Pandas DataFrame</center></h1></b>

# **DataFrame**
**A DataFrame is a two-dimensional labeled data structure consisting of rows and columns.**

**Think of it as an Excel spreadsheet or a SQL table.**

| Name  | Age | Marks | City      |
| ----- | --: | ----: | --------- |
| Ali   |  20 |    85 | Peshawar  |
| Ahmed |  22 |    90 | Lahore    |
| Sara  |  21 |    75 | Karachi   |
| Usman |  23 |    95 | Islamabad |


This entire table is a DataFrame.

**In simple word:**

**A DataFrame is a two-dimensional data structure made up of multiple Series that share the same index.**

Python internally store it like this.

```
                DataFrame
        ┌────────────────────────┐
        │ Name │ Age │ Marks     │
────────┼────────────────────────┤
0       │ Ali  │ 20  │ 85        │
1       │Ahmed │ 22  │ 90        │
2       │Sara  │ 21  │ 75        │
────────┴────────────────────────┘
```

Each column is a series

```
DataFrame

       Name Series
0      Ali
1      Ahmed
2      Sara

       Age Series
0      20
1      22
2      21

      Marks Series
0      85
1      90
2      75
```

So actually DataFrame is a collection of Series
```
DataFrame
      │
      ▼
Collection of Series
```

In [289]:
# we have to import the pandas and the recomended way is whenever you import the pandas you have to import the numpy as well
import numpy as np
import pandas as pd
import warnings

warnings.filterwarnings('ignore')

<br>

# **Creating of DataFrame**

### **creating from Dictionary**
By creating dataframe from dictionary each key become column of dataframe and each value(list) of dictionary become values of column

In [290]:

data = {
    "Name":["Ali","Ahmed","Sara"],
    "Age":[20,22,21],
    "Marks":[85,90,75]
}

df = pd.DataFrame(data)

df

    Name  Age  Marks
0    Ali   20     85
1  Ahmed   22     90
2   Sara   21     75

### **creting from Dictionary of Series**

In [291]:
names = pd.Series(["Ali","Ahmed","Sara"])

ages = pd.Series([20,22,21])

marks = pd.Series([85,90,75])

dic = {
    "Name":names, 
    "Age":ages,
    "Marks":marks
}

df = pd.DataFrame(dic)

df

    Name  Age  Marks
0    Ali   20     85
1  Ahmed   22     90
2   Sara   21     75

### **creating with 2D List**
When you created any Dataframe from list you have to mentioned the name of columns in the dataframe. Without mentioning the columns it will give index to the column by default.

In [292]:
li = [
    ["salman", 34, 45, 67], 
    ["naveed", 32, 54, 65],
    ["ubaid", 34, 54, 76]
]

df = pd.DataFrame(li, columns=["Names", "Math", "Pak", "Science"])
df

    Names  Math  Pak  Science
0  salman    34   45       67
1  naveed    32   54       65
2   ubaid    34   54       76

In [293]:
# We can also change the index and label the index of dataframe

li = [
    ["salman", 34, 45, 67], 
    ["naveed", 32, 54, 65],
    ["ubaid", 34, 54, 76]
]

df = pd.DataFrame(li, columns=["Names", "Math", "Pak", "Science"], index=["A", "B", "C"])
df

    Names  Math  Pak  Science
A  salman    34   45       67
B  naveed    32   54       65
C   ubaid    34   54       76

In [294]:
# We can also change the index with column 
li = [
    ["salman", 34, 45, 67], 
    ["naveed", 32, 54, 65],
    ["ubaid", 34, 54, 76]
]

df = pd.DataFrame(li, columns=["Names", "Math", "Pak", "Science"])
df.set_index("Names")

        Math  Pak  Science
Names
salman    34   45       67
naveed    32   54       65
ubaid     34   54       76

In [295]:
# we can also reset the index with its defualt index and the column will again become column(series)
df.reset_index()

   index   Names  Math  Pak  Science
0      0  salman    34   45       67
1      1  naveed    32   54       65
2      2   ubaid    34   54       76

### **creating from List of Dictionaries**

In [296]:
data = [
    {"Name":"Ali","Age":20,"Marks":85},
    {"Name":"Ahmed","Age":22,"Marks":90},
    {"Name":"Sara","Age":21,"Marks":75}
]

df = pd.DataFrame(data)

df

    Name  Age  Marks
0    Ali   20     85
1  Ahmed   22     90
2   Sara   21     75

### **creating from numpy array**

In [297]:
# the process is same like list

arr = np.array([
    [20,85],
    [22,90],
    [21,75]
])

df = pd.DataFrame(
    arr,
    columns=["Age","Marks"]
)

df

   Age  Marks
0   20     85
1   22     90
2   21     75

### **creting with scalor value**
A single scalor will repeat according to index and columns.

In [298]:
pd.DataFrame(100, index=[i for i in range(1, 11)], columns=["NO_1", "NO_2"])    # i used list comprehension for index to generate 1 to 10 index

    NO_1  NO_2
1    100   100
2    100   100
3    100   100
4    100   100
5    100   100
6    100   100
7    100   100
8    100   100
9    100   100
10   100   100

In [299]:
pd.DataFrame("salman", index=[3, 4, 5, 6], columns=["Name"])

     Name
3  salman
4  salman
5  salman
6  salman

In [300]:
pd.DataFrame([["salman",100]], index=[0, 1, 2, 3, 4, 5], columns=["Name", "Marks"])

     Name  Marks
0  salman    100
1  salman    100
2  salman    100
3  salman    100
4  salman    100
5  salman    100

### **creating with specific datatype**

In [301]:
li = [
    [1, 2, 3, 4],
    [3, 4, 6, 7]
]

pd.DataFrame(li, columns=["eng", "math", "bio", "cs"], dtype='float16')

   eng  math  bio   cs
0  1.0   2.0  3.0  4.0
1  3.0   4.0  6.0  7.0

# **Series Vs DataFrame**

| Feature    | Series        | DataFrame                   |
| ---------- | ------------- | --------------------------- |
| Dimensions | 1D            | 2D                          |
| Structure  | One column    | Multiple columns            |
| Data Type  | Single axis   | Rows and columns            |
| Index      | Yes           | Row index and column labels |
| Example    | Student marks | Complete student table      |

<br>

# **Loading DataFrame from Dataset**

In [302]:
movies = pd.read_csv('data/17_data/movies.csv')
movies.head(2)

,title_x,imdb_id,poster_path,wiki_link,title_y,original_title,is_adult,year_of_release,runtime,genres,imdb_rating,imdb_votes,story,summary,tagline,actors,wins_nominations,release_date
0,Uri: The Surgical Strike,tt8291224,https://upload.wikimedia.org/wikipedia/en/thum...,https://en.wikipedia.org/wiki/Uri:_The_Surgica...,Uri: The Surgical Strike,Uri: The Surgical Strike,0,2019,138,Action|Drama|War,8.4,35112,Divided over five chapters the film chronicle...,Indian army special forces execute a covert op...,NaN,Vicky Kaushal|Paresh Rawal|Mohit Raina|Yami Ga...,4 wins,11 January 2019 (USA)
1,Battalion 609,tt9472208,NaN,https://en.wikipedia.org/wiki/Battalion_609,Battalion 609,Battalion 609,0,2019,131,War,4.1,73,The story revolves around a cricket match betw...,The story of Battalion 609 revolves around a c...,NaN,Vicky Ahuja|Shoaib Ibrahim|Shrikant Kamat|Elen...,NaN,11 January 2019 (India)

In [303]:
# we can use column as an index
pd.read_csv('data/17_data/movies.csv', index_col=["title_x"]).head(2)

,imdb_id,poster_path,wiki_link,title_y,original_title,is_adult,year_of_release,runtime,genres,imdb_rating,imdb_votes,story,summary,tagline,actors,wins_nominations,release_date
title_x,,,,,,,,,,,,,,,,,
Uri: The Surgical Strike,tt8291224,https://upload.wikimedia.org/wikipedia/en/thum...,https://en.wikipedia.org/wiki/Uri:_The_Surgica...,Uri: The Surgical Strike,Uri: The Surgical Strike,0,2019,138,Action|Drama|War,8.4,35112,Divided over five chapters the film chronicle...,Indian army special forces execute a covert op...,NaN,Vicky Kaushal|Paresh Rawal|Mohit Raina|Yami Ga...,4 wins,11 January 2019 (USA)
Battalion 609,tt9472208,NaN,https://en.wikipedia.org/wiki/Battalion_609,Battalion 609,Battalion 609,0,2019,131,War,4.1,73,The story revolves around a cricket match betw...,The story of Battalion 609 revolves around a c...,NaN,Vicky Ahuja|Shoaib Ibrahim|Shrikant Kamat|Elen...,NaN,11 January 2019 (India)

In [304]:
# we can use only one column from a dataset
pd.read_csv('data/17_data/movies.csv', usecols=['original_title']).head(2)

             original_title
0  Uri: The Surgical Strike
1             Battalion 609

In [305]:
ipl = pd.read_csv("data/17_data/ipl-matches.csv")
ipl.head(2)

,ID,City,Date,Season,MatchNumber,Team1,Team2,Venue,TossWinner,TossDecision,SuperOver,WinningTeam,WonBy,Margin,method,Player_of_Match,Team1Players,Team2Players,Umpire1,Umpire2
0,1312200,Ahmedabad,2022-05-29,2022,Final,Rajasthan Royals,Gujarat Titans,"Narendra Modi Stadium, Ahmedabad",Rajasthan Royals,bat,N,Gujarat Titans,Wickets,7.0,NaN,HH Pandya,"['YBK Jaiswal', 'JC Buttler', 'SV Samson', 'D ...","['WP Saha', 'Shubman Gill', 'MS Wade', 'HH Pan...",CB Gaffaney,Nitin Menon
1,1312199,Ahmedabad,2022-05-27,2022,Qualifier 2,Royal Challengers Bangalore,Rajasthan Royals,"Narendra Modi Stadium, Ahmedabad",Rajasthan Royals,field,N,Rajasthan Royals,Wickets,7.0,NaN,JC Buttler,"['V Kohli', 'F du Plessis', 'RM Patidar', 'GJ ...","['YBK Jaiswal', 'JC Buttler', 'SV Samson', 'D ...",CB Gaffaney,Nitin Menon

<br>

# **DataFrame Attribute**
Attributes do not have parentheses () because they return information about the DataFrame.

Methods have parentheses () because they perform an action.

### **shape**
Shape return the number of rows and number of columns in the dataframe.

In [306]:
movies.shape   # the first values represent number of rows and second number represent number of columns.

(1629, 18)

<br>

### **Size**
It return the total number of values persent in the dataframe. (rows * columns)

In [307]:
movies.size

29322

### **dtypes**
dtypes means Data Types.

It tells you:

"What type of data is stored in this DataFrame?"

In [308]:
movies.dtypes

title_x                 str
imdb_id                 str
poster_path             str
wiki_link               str
title_y                 str
original_title          str
is_adult              int64
year_of_release       int64
runtime                 str
genres                  str
imdb_rating         float64
imdb_votes            int64
story                   str
summary                 str
tagline                 str
actors                  str
wins_nominations        str
release_date            str
dtype: object

### **index**
This returns the labels/index of the dataframe.

In [309]:
movies.index     # it retunn the range of index as start form 0 and stop on 4 as 4 is not included and there is only one step

RangeIndex(start=0, stop=1629, step=1)

In [310]:
ipl.set_index(['ID']).index         # set index set the index of dataframe as ID column

Index([1312200, 1312199, 1312198, 1312197, 1304116, 1304115, 1304114, 1304113,
       1304112, 1304111,
       ...
        335991,  335990,  335989,  335988,  335987,  335986,  335985,  335984,
        335983,  335982],
      dtype='int64', name='ID', length=950)

### **values**
This returns all the data/record stored in the DataFrame, without the index.

It return a 2D arrray where each array inside a 2D array is one record(row)

In [311]:
movies.values
ipl.values

array([[1312200, 'Ahmedabad', '2022-05-29', ...,
        "['WP Saha', 'Shubman Gill', 'MS Wade', 'HH Pandya', 'DA Miller', 'R Tewatia', 'Rashid Khan', 'R Sai Kishore', 'LH Ferguson', 'Yash Dayal', 'Mohammed Shami']",
        'CB Gaffaney', 'Nitin Menon'],
       [1312199, 'Ahmedabad', '2022-05-27', ...,
        "['YBK Jaiswal', 'JC Buttler', 'SV Samson', 'D Padikkal', 'SO Hetmyer', 'R Parag', 'R Ashwin', 'TA Boult', 'YS Chahal', 'M Prasidh Krishna', 'OC McCoy']",
        'CB Gaffaney', 'Nitin Menon'],
       [1312198, 'Kolkata', '2022-05-25', ...,
        "['Q de Kock', 'KL Rahul', 'M Vohra', 'DJ Hooda', 'MP Stoinis', 'E Lewis', 'KH Pandya', 'PVD Chameera', 'Mohsin Khan', 'Avesh Khan', 'Ravi Bishnoi']",
        'J Madanagopal', 'MA Gough'],
       ...,
       [335984, 'Delhi', '2008-04-19', ...,
        "['T Kohli', 'YK Pathan', 'SR Watson', 'M Kaif', 'DS Lehmann', 'RA Jadeja', 'M Rawat', 'D Salunkhe', 'SK Warne', 'SK Trivedi', 'MM Patel']",
        'Aleem Dar', 'GA Pratapkumar'],
       [335983, 'Chandigarh', '2008-04-19', ...,
        "['PA Patel', 'ML Hayden', 'MEK Hussey', 'MS Dhoni', 'SK Raina', 'JDP Oram', 'S Badrinath', 'Joginder Sharma', 'P Amarnath', 'MS Gony', 'M Muralitharan']",
        'MR Benson', 'SL Shastri'],
       [335982, 'Bangalore', '2008-04-18', ...,
        "['SC Ganguly', 'BB McCullum', 'RT Ponting', 'DJ Hussey', 'Mohammad Hafeez', 'LR Shukla', 'WP Saha', 'AB Agarkar', 'AB Dinda', 'M Kartik', 'I Sharma']",
        'Asad Rauf', 'RE Koertzen']], shape=(950, 20), dtype=object)

### **columns**
This returns all the columns of the dataframe.

In [312]:
movies.columns

Index(['title_x', 'imdb_id', 'poster_path', 'wiki_link', 'title_y',
       'original_title', 'is_adult', 'year_of_release', 'runtime', 'genres',
       'imdb_rating', 'imdb_votes', 'story', 'summary', 'tagline', 'actors',
       'wins_nominations', 'release_date'],
      dtype='str')

In [313]:
ipl.columns

Index(['ID', 'City', 'Date', 'Season', 'MatchNumber', 'Team1', 'Team2',
       'Venue', 'TossWinner', 'TossDecision', 'SuperOver', 'WinningTeam',
       'WonBy', 'Margin', 'method', 'Player_of_Match', 'Team1Players',
       'Team2Players', 'Umpire1', 'Umpire2'],
      dtype='str')

<br>

# **Summary**

| Attribute   | Purpose                         | Returns                            |
| ----------- | ------------------------------- | ---------------------------------- |
| `size`      | Number of elements(row*col)     | Integer                            |
| `dtype`     | Data type of the values         | `int64`, `float64`, `object`, etc. |
| `index`     | Returns the labels (indexes)    | `Index` object                     |
| `values`    | Returns only the data           | Usually a NumPy array (`ndarray`)  |
| `columns`   | Returns all the columns         | Usually a NumPy array (`ndarray`)  |

<br>

# **DataFrame Methods**

### **head()**

it give the head of dataframe same like series.

In [314]:
movies.head()    # by default it give 5 rows

,title_x,imdb_id,poster_path,wiki_link,title_y,original_title,is_adult,year_of_release,runtime,genres,imdb_rating,imdb_votes,story,summary,tagline,actors,wins_nominations,release_date
0,Uri: The Surgical Strike,tt8291224,https://upload.wikimedia.org/wikipedia/en/thum...,https://en.wikipedia.org/wiki/Uri:_The_Surgica...,Uri: The Surgical Strike,Uri: The Surgical Strike,0,2019,138,Action|Drama|War,8.4,35112,Divided over five chapters the film chronicle...,Indian army special forces execute a covert op...,NaN,Vicky Kaushal|Paresh Rawal|Mohit Raina|Yami Ga...,4 wins,11 January 2019 (USA)
1,Battalion 609,tt9472208,NaN,https://en.wikipedia.org/wiki/Battalion_609,Battalion 609,Battalion 609,0,2019,131,War,4.1,73,The story revolves around a cricket match betw...,The story of Battalion 609 revolves around a c...,NaN,Vicky Ahuja|Shoaib Ibrahim|Shrikant Kamat|Elen...,NaN,11 January 2019 (India)
2,The Accidental Prime Minister (film),tt6986710,https://upload.wikimedia.org/wikipedia/en/thum...,https://en.wikipedia.org/wiki/The_Accidental_P...,The Accidental Prime Minister,The Accidental Prime Minister,0,2019,112,Biography|Drama,6.1,5549,Based on the memoir by Indian policy analyst S...,Explores Manmohan Singh's tenure as the Prime ...,NaN,Anupam Kher|Akshaye Khanna|Aahana Kumra|Atul S...,NaN,11 January 2019 (USA)
3,Why Cheat India,tt8108208,https://upload.wikimedia.org/wikipedia/en/thum...,https://en.wikipedia.org/wiki/Why_Cheat_India,Why Cheat India,Why Cheat India,0,2019,121,Crime|Drama,6.0,1891,The movie focuses on existing malpractices in ...,The movie focuses on existing malpractices in ...,NaN,Emraan Hashmi|Shreya Dhanwanthary|Snighdadeep ...,NaN,18 January 2019 (USA)
4,Evening Shadows,tt6028796,NaN,https://en.wikipedia.org/wiki/Evening_Shadows,Evening Shadows,Evening Shadows,0,2018,102,Drama,7.3,280,While gay rights and marriage equality has bee...,Under the 'Evening Shadows' truth often plays...,NaN,Mona Ambegaonkar|Ananth Narayan Mahadevan|Deva...,17 wins & 1 nomination,11 January 2019 (India)

In [315]:
movies.head(3) # we can mentioned the number of rows

,title_x,imdb_id,poster_path,wiki_link,title_y,original_title,is_adult,year_of_release,runtime,genres,imdb_rating,imdb_votes,story,summary,tagline,actors,wins_nominations,release_date
0,Uri: The Surgical Strike,tt8291224,https://upload.wikimedia.org/wikipedia/en/thum...,https://en.wikipedia.org/wiki/Uri:_The_Surgica...,Uri: The Surgical Strike,Uri: The Surgical Strike,0,2019,138,Action|Drama|War,8.4,35112,Divided over five chapters the film chronicle...,Indian army special forces execute a covert op...,NaN,Vicky Kaushal|Paresh Rawal|Mohit Raina|Yami Ga...,4 wins,11 January 2019 (USA)
1,Battalion 609,tt9472208,NaN,https://en.wikipedia.org/wiki/Battalion_609,Battalion 609,Battalion 609,0,2019,131,War,4.1,73,The story revolves around a cricket match betw...,The story of Battalion 609 revolves around a c...,NaN,Vicky Ahuja|Shoaib Ibrahim|Shrikant Kamat|Elen...,NaN,11 January 2019 (India)
2,The Accidental Prime Minister (film),tt6986710,https://upload.wikimedia.org/wikipedia/en/thum...,https://en.wikipedia.org/wiki/The_Accidental_P...,The Accidental Prime Minister,The Accidental Prime Minister,0,2019,112,Biography|Drama,6.1,5549,Based on the memoir by Indian policy analyst S...,Explores Manmohan Singh's tenure as the Prime ...,NaN,Anupam Kher|Akshaye Khanna|Aahana Kumra|Atul S...,NaN,11 January 2019 (USA)

### **tail()**

it give the tail of dataframe

In [316]:
movies.tail()

,title_x,imdb_id,poster_path,wiki_link,title_y,original_title,is_adult,year_of_release,runtime,genres,imdb_rating,imdb_votes,story,summary,tagline,actors,wins_nominations,release_date
1624,Tera Mera Saath Rahen,tt0301250,https://upload.wikimedia.org/wikipedia/en/2/2b...,https://en.wikipedia.org/wiki/Tera_Mera_Saath_...,Tera Mera Saath Rahen,Tera Mera Saath Rahen,0,2001,148,Drama,4.9,278,Raj Dixit lives with his younger brother Rahu...,A man is torn between his handicapped brother ...,NaN,Ajay Devgn|Sonali Bendre|Namrata Shirodkar|Pre...,NaN,7 November 2001 (India)
1625,Yeh Zindagi Ka Safar,tt0298607,https://upload.wikimedia.org/wikipedia/en/thum...,https://en.wikipedia.org/wiki/Yeh_Zindagi_Ka_S...,Yeh Zindagi Ka Safar,Yeh Zindagi Ka Safar,0,2001,146,Drama,3.0,133,Hindi pop-star Sarina Devan lives a wealthy ...,A singer finds out she was adopted when the ed...,NaN,Ameesha Patel|Jimmy Sheirgill|Nafisa Ali|Gulsh...,NaN,16 November 2001 (India)
1626,Sabse Bada Sukh,tt0069204,NaN,https://en.wikipedia.org/wiki/Sabse_Bada_Sukh,Sabse Bada Sukh,Sabse Bada Sukh,0,2018,\N,Comedy|Drama,6.1,13,Village born Lalloo re-locates to Bombay and ...,Village born Lalloo re-locates to Bombay and ...,NaN,Vijay Arora|Asrani|Rajni Bala|Kumud Damle|Utpa...,NaN,NaN
1627,Daaka,tt10833860,https://upload.wikimedia.org/wikipedia/en/thum...,https://en.wikipedia.org/wiki/Daaka,Daaka,Daaka,0,2019,136,Action,7.4,38,Shinda tries robbing a bank so he can be wealt...,Shinda tries robbing a bank so he can be wealt...,NaN,Gippy Grewal|Zareen Khan|,NaN,1 November 2019 (USA)
1628,Humsafar,tt2403201,https://upload.wikimedia.org/wikipedia/en/thum...,https://en.wikipedia.org/wiki/Humsafar,Humsafar,Humsafar,0,2011,35,Drama|Romance,9.0,2968,Sara and Ashar are childhood friends who share...,Ashar and Khirad are forced to get married due...,NaN,Fawad Khan|,NaN,TV Series (2011–2012)

In [317]:
movies.tail(2)

,title_x,imdb_id,poster_path,wiki_link,title_y,original_title,is_adult,year_of_release,runtime,genres,imdb_rating,imdb_votes,story,summary,tagline,actors,wins_nominations,release_date
1627,Daaka,tt10833860,https://upload.wikimedia.org/wikipedia/en/thum...,https://en.wikipedia.org/wiki/Daaka,Daaka,Daaka,0,2019,136,Action,7.4,38,Shinda tries robbing a bank so he can be wealt...,Shinda tries robbing a bank so he can be wealt...,NaN,Gippy Grewal|Zareen Khan|,NaN,1 November 2019 (USA)
1628,Humsafar,tt2403201,https://upload.wikimedia.org/wikipedia/en/thum...,https://en.wikipedia.org/wiki/Humsafar,Humsafar,Humsafar,0,2011,35,Drama|Romance,9.0,2968,Sara and Ashar are childhood friends who share...,Ashar and Khirad are forced to get married due...,NaN,Fawad Khan|,NaN,TV Series (2011–2012)

### **sample()**

it give random row/record from a dataframe

In [318]:
movies.sample()

,title_x,imdb_id,poster_path,wiki_link,title_y,original_title,is_adult,year_of_release,runtime,genres,imdb_rating,imdb_votes,story,summary,tagline,actors,wins_nominations,release_date
123,Satyameva Jayate (2018 film),tt8202612,https://upload.wikimedia.org/wikipedia/en/thum...,https://en.wikipedia.org/wiki/Satyameva_Jayate...,Satyameva Jayate,Satyameva Jayate,0,2018,140,Action|Thriller,5.6,5446,There are about 2 Lakh policemen in Mumbai. Ta...,DCP Shivansh has been tasked to catch Vir the...,Beimaan pitega| corruption mitega!,John Abraham|Manoj Bajpayee|Aisha Sharma|Amrut...,5 nominations,15 August 2018 (USA)

In [319]:
movies.sample(3)

,title_x,imdb_id,poster_path,wiki_link,title_y,original_title,is_adult,year_of_release,runtime,genres,imdb_rating,imdb_votes,story,summary,tagline,actors,wins_nominations,release_date
536,Haider (film),tt3390572,https://upload.wikimedia.org/wikipedia/en/thum...,https://en.wikipedia.org/wiki/Haider_(film),Haider,Haider,0,2014,160,Action|Crime|Drama,8.1,46912,Vishal Bhardwaj's adaptation of William Shakes...,A young man returns to Kashmir after his fathe...,NaN,Tabu|Shahid Kapoor|Shraddha Kapoor|Kay Kay Men...,28 wins & 24 nominations,2 October 2014 (USA)
1235,D (film),tt0454435,https://upload.wikimedia.org/wikipedia/en/thum...,https://en.wikipedia.org/wiki/D_(film),'D','D',0,2005,107,Crime|Drama|Thriller,6.8,1126,After his mother passes away Mumbai-based Des...,Deshu a mechanic from Dubai comes home to Mu...,NaN,Randeep Hooda|Chunky Pandey|Rukhsar Rehman|Ish...,NaN,3 June 2005 (India)
967,Jail (2009 film),tt1245774,https://upload.wikimedia.org/wikipedia/en/thum...,https://en.wikipedia.org/wiki/Jail_(2009_film),Jail,Jail,0,2009,131,Drama,6.2,1097,Shortly after getting promoted as Regional Man...,Remanded to policy custody a man reviews his ...,NaN,Manoj Bajpayee|Neil Nitin Mukesh|Atul Kulkarni...,1 nomination,6 November 2009 (India)

### **info()**

This return some inforamtion about the dataframe

In [320]:
movies.info()

<class 'pandas.DataFrame'>
RangeIndex: 1629 entries, 0 to 1628
Data columns (total 18 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   title_x           1629 non-null   str
 1   imdb_id           1629 non-null   str
 2   poster_path       1526 non-null   str
 3   wiki_link         1629 non-null   str
 4   title_y           1629 non-null   str
 5   original_title    1629 non-null   str
 6   is_adult          1629 non-null   int64
 7   year_of_release   1629 non-null   int64
 8   runtime           1629 non-null   str
 9   genres            1629 non-null   str
 10  imdb_rating       1629 non-null   float64
 11  imdb_votes        1629 non-null   int64
 12  story             1609 non-null   str
 13  summary           1629 non-null   str
 14  tagline           557 non-null    str
 15  actors            1624 non-null   str
 16  wins_nominations  707 non-null    str
 17  release_date      1522 non-null   str
dtypes: float64(1), int64(3), str(14)
memory usage: 2.0 MB

### **describe()**
It give some math information about dataframe.

In [321]:
movies.describe()

       is_adult  year_of_release  imdb_rating     imdb_votes
count    1629.0      1629.000000  1629.000000    1629.000000
mean        0.0      2010.263966     5.557459    5384.263352
std         0.0         5.381542     1.567609   14552.103231
min         0.0      2001.000000     0.000000       0.000000
25%         0.0      2005.000000     4.400000     233.000000
50%         0.0      2011.000000     5.600000    1000.000000
75%         0.0      2015.000000     6.800000    4287.000000
max         0.0      2019.000000     9.400000  310481.000000

In [322]:
ipl.describe()

                 ID      Margin
count  9.500000e+02  932.000000
mean   8.304852e+05   17.056867
std    3.375678e+05   21.633109
min    3.359820e+05    1.000000
25%    5.012612e+05    6.000000
50%    8.297380e+05    8.000000
75%    1.175372e+06   19.000000
max    1.312200e+06  146.000000

<br>

# **DataFrame Math Methods**

All the math methods by default work on columns by defualt. 

In order to apply methods on row we have to change the axis=1 and by defualt it is axis=0.

### **count()**
It will count the number of rows without counting the null values or row.

In [323]:
movies.count()         # total record without null

title_x             1629
imdb_id             1629
poster_path         1526
wiki_link           1629
title_y             1629
original_title      1629
is_adult            1629
year_of_release     1629
runtime             1629
genres              1629
imdb_rating         1629
imdb_votes          1629
story               1609
summary             1629
tagline              557
actors              1624
wins_nominations     707
release_date        1522
dtype: int64

In [324]:
movies.count(axis=1)

0       17
1       15
2       16
3       16
4       16
        ..
1624    16
1625    16
1626    14
1627    16
1628    16
Length: 1629, dtype: int64

### **sum()**
Give the sum of values

In [325]:
s = pd.DataFrame([[22, 33, 44], [55, 44, 34], [65, 45,32]], columns=['math', 'cs', 'bio'], index=['salman', 'ali', 'ahmand'])
s

        math  cs  bio
salman    22  33   44
ali       55  44   34
ahmand    65  45   32

In [326]:
s.sum()       # it give us sum on the basis of columns

math    142
cs      122
bio     110
dtype: int64

In [327]:
# we can also sum the values on the basis of row by changing the axis
s.sum(axis=1)

salman     99
ali       133
ahmand    142
dtype: int64

### **product()**
give product of values

In [328]:
s.product()

math    78650
cs      65340
bio     47872
dtype: int64

In [329]:
s.product(axis=1)

salman    31944
ali       82280
ahmand    93600
dtype: int64

### **mean()**
It give the average of values

In [330]:
s.mean()

math    47.333333
cs      40.666667
bio     36.666667
dtype: float64

In [331]:
s.mean(axis=1)

salman    33.000000
ali       44.333333
ahmand    47.333333
dtype: float64

### **median()**
It give the median of values.

In [332]:
s.median()

math    55.0
cs      44.0
bio     34.0
dtype: float64

In [333]:
s.median(axis=1)

salman    33.0
ali       44.0
ahmand    45.0
dtype: float64

### **mode()**
It give the most frequent values in series.

In [334]:
s['che']=[44, 55, 65]   # just ignore this for now and think like i add a new column of chemistry marks
s

        math  cs  bio  che
salman    22  33   44   44
ali       55  44   34   55
ahmand    65  45   32   65

In [335]:
s.mode()  # column mode

   math  cs  bio  che
0    22  33   32   44
1    55  44   34   55
2    65  45   44   65

In [336]:
s.mode(axis=1)          # row mode

         0
salman  44
ali     55
ahmand  65

### **std()**
it give standard deviation of dataframe values.

In [337]:
s.std()

math    22.501852
cs       6.658328
bio      6.429101
che     10.503968
dtype: float64

In [338]:
s.std(axis=1)

salman    10.531698
ali       10.099505
ahmand    16.194135
dtype: float64

### **var()**
it give variation of dataframe values.

In [339]:
s.var()

math    506.333333
cs       44.333333
bio      41.333333
che     110.333333
dtype: float64

In [340]:
s.var(axis=1)

salman    110.916667
ali       102.000000
ahmand    262.250000
dtype: float64

### **min()**
it give minimiun value of dataframe values.

In [341]:
s.min()

math    22
cs      33
bio     32
che     44
dtype: int64

In [342]:
s.min(axis=1)

salman    22
ali       34
ahmand    32
dtype: int64

### **max()**
it give maximium value of dataframe values.

In [343]:
s.max()

math    65
cs      45
bio     44
che     65
dtype: int64

In [344]:
s.max(axis=1)

salman    44
ali       55
ahmand    65
dtype: int64

<br>

# **Selecting Columns from DataFrame**

### **Selecting single columns**

In [345]:
movies.head(2)

,title_x,imdb_id,poster_path,wiki_link,title_y,original_title,is_adult,year_of_release,runtime,genres,imdb_rating,imdb_votes,story,summary,tagline,actors,wins_nominations,release_date
0,Uri: The Surgical Strike,tt8291224,https://upload.wikimedia.org/wikipedia/en/thum...,https://en.wikipedia.org/wiki/Uri:_The_Surgica...,Uri: The Surgical Strike,Uri: The Surgical Strike,0,2019,138,Action|Drama|War,8.4,35112,Divided over five chapters the film chronicle...,Indian army special forces execute a covert op...,NaN,Vicky Kaushal|Paresh Rawal|Mohit Raina|Yami Ga...,4 wins,11 January 2019 (USA)
1,Battalion 609,tt9472208,NaN,https://en.wikipedia.org/wiki/Battalion_609,Battalion 609,Battalion 609,0,2019,131,War,4.1,73,The story revolves around a cricket match betw...,The story of Battalion 609 revolves around a c...,NaN,Vicky Ahuja|Shoaib Ibrahim|Shrikant Kamat|Elen...,NaN,11 January 2019 (India)

In [346]:
movies["title_x"]

0                   Uri: The Surgical Strike
1                              Battalion 609
2       The Accidental Prime Minister (film)
3                            Why Cheat India
4                            Evening Shadows
                        ...
1624                   Tera Mera Saath Rahen
1625                    Yeh Zindagi Ka Safar
1626                         Sabse Bada Sukh
1627                                   Daaka
1628                                Humsafar
Name: title_x, Length: 1629, dtype: str

In [347]:
ipl['City']

0       Ahmedabad
1       Ahmedabad
2         Kolkata
3         Kolkata
4          Mumbai
          ...
945       Kolkata
946        Mumbai
947         Delhi
948    Chandigarh
949     Bangalore
Name: City, Length: 950, dtype: str

In [348]:
ipl["City"].head(2)

0    Ahmedabad
1    Ahmedabad
Name: City, dtype: str

<br>

### **Selecting Multiple columns**

In [349]:
movies[["title_x", "poster_path"]]

,title_x,poster_path
0,Uri: The Surgical Strike,https://upload.wikimedia.org/wikipedia/en/thum...
1,Battalion 609,NaN
2,The Accidental Prime Minister (film),https://upload.wikimedia.org/wikipedia/en/thum...
3,Why Cheat India,https://upload.wikimedia.org/wikipedia/en/thum...
4,Evening Shadows,NaN
...,...,...
1624,Tera Mera Saath Rahen,https://upload.wikimedia.org/wikipedia/en/2/2b...
1625,Yeh Zindagi Ka Safar,https://upload.wikimedia.org/wikipedia/en/thum...
1626,Sabse Bada Sukh,NaN
1627,Daaka,https://upload.wikimedia.org/wikipedia/en/thum...
1628,Humsafar,https://upload.wikimedia.org/wikipedia/en/thum...

In [350]:
movies[["title_y", "original_title", "is_adult"]]

                            title_y                 original_title  is_adult
0          Uri: The Surgical Strike       Uri: The Surgical Strike         0
1                     Battalion 609                  Battalion 609         0
2     The Accidental Prime Minister  The Accidental Prime Minister         0
3                   Why Cheat India                Why Cheat India         0
4                   Evening Shadows                Evening Shadows         0
...                             ...                            ...       ...
1624          Tera Mera Saath Rahen          Tera Mera Saath Rahen         0
1625           Yeh Zindagi Ka Safar           Yeh Zindagi Ka Safar         0
1626                Sabse Bada Sukh                Sabse Bada Sukh         0
1627                          Daaka                          Daaka         0
1628                       Humsafar                       Humsafar         0

[1629 rows x 3 columns]

<br>

# **Selecting Rows from DataFrame**

We can can apply the whole same concept of series indexing, label indexing, slicing and fancy indexing on dataframe to access any row or rows.

- **iloc** - searches using index positions
- **loc** - searches using index labels

You should mention the searching method that whethere you search on the basis of index or lobel.

### **Selecting single row**

It give a series of single row

In [351]:
movies.iloc[0]

title_x                                      Uri: The Surgical Strike
imdb_id                                                     tt8291224
poster_path         https://upload.wikimedia.org/wikipedia/en/thum...
wiki_link           https://en.wikipedia.org/wiki/Uri:_The_Surgica...
title_y                                      Uri: The Surgical Strike
original_title                               Uri: The Surgical Strike
is_adult                                                            0
year_of_release                                                  2019
runtime                                                           138
genres                                               Action|Drama|War
imdb_rating                                                       8.4
imdb_votes                                                      35112
story               Divided over five chapters  the film chronicle...
summary             Indian army special forces execute a covert op...
tagline                                                           NaN
actors              Vicky Kaushal|Paresh Rawal|Mohit Raina|Yami Ga...
wins_nominations                                               4 wins
release_date                                    11 January 2019 (USA)
Name: 0, dtype: object

In [352]:

ipl.set_index(["ID"]).loc[1312199]       # it give the row by label which is id

City                                                       Ahmedabad
Date                                                      2022-05-27
Season                                                          2022
MatchNumber                                              Qualifier 2
Team1                                    Royal Challengers Bangalore
Team2                                               Rajasthan Royals
Venue                               Narendra Modi Stadium, Ahmedabad
TossWinner                                          Rajasthan Royals
TossDecision                                                   field
SuperOver                                                          N
WinningTeam                                         Rajasthan Royals
WonBy                                                        Wickets
Margin                                                           7.0
method                                                           NaN
Player_of_Match                                           JC Buttler
Team1Players       ['V Kohli', 'F du Plessis', 'RM Patidar', 'GJ ...
Team2Players       ['YBK Jaiswal', 'JC Buttler', 'SV Samson', 'D ...
Umpire1                                                  CB Gaffaney
Umpire2                                                  Nitin Menon
Name: 1312199, dtype: object

In [353]:
ipl.set_index(["ID"]).iloc[1]      # we can also access a label index dataframe with its index as it have also hidden index

City                                                       Ahmedabad
Date                                                      2022-05-27
Season                                                          2022
MatchNumber                                              Qualifier 2
Team1                                    Royal Challengers Bangalore
Team2                                               Rajasthan Royals
Venue                               Narendra Modi Stadium, Ahmedabad
TossWinner                                          Rajasthan Royals
TossDecision                                                   field
SuperOver                                                          N
WinningTeam                                         Rajasthan Royals
WonBy                                                        Wickets
Margin                                                           7.0
method                                                           NaN
Player_of_Match                                           JC Buttler
Team1Players       ['V Kohli', 'F du Plessis', 'RM Patidar', 'GJ ...
Team2Players       ['YBK Jaiswal', 'JC Buttler', 'SV Samson', 'D ...
Umpire1                                                  CB Gaffaney
Umpire2                                                  Nitin Menon
Name: 1312199, dtype: object

<br>

### **Selecting multiple rows**
We can also access multiple rows

In [354]:
movies[0:2]

,title_x,imdb_id,poster_path,wiki_link,title_y,original_title,is_adult,year_of_release,runtime,genres,imdb_rating,imdb_votes,story,summary,tagline,actors,wins_nominations,release_date
0,Uri: The Surgical Strike,tt8291224,https://upload.wikimedia.org/wikipedia/en/thum...,https://en.wikipedia.org/wiki/Uri:_The_Surgica...,Uri: The Surgical Strike,Uri: The Surgical Strike,0,2019,138,Action|Drama|War,8.4,35112,Divided over five chapters the film chronicle...,Indian army special forces execute a covert op...,NaN,Vicky Kaushal|Paresh Rawal|Mohit Raina|Yami Ga...,4 wins,11 January 2019 (USA)
1,Battalion 609,tt9472208,NaN,https://en.wikipedia.org/wiki/Battalion_609,Battalion 609,Battalion 609,0,2019,131,War,4.1,73,The story revolves around a cricket match betw...,The story of Battalion 609 revolves around a c...,NaN,Vicky Ahuja|Shoaib Ibrahim|Shrikant Kamat|Elen...,NaN,11 January 2019 (India)

In [355]:
movies[1626:]

,title_x,imdb_id,poster_path,wiki_link,title_y,original_title,is_adult,year_of_release,runtime,genres,imdb_rating,imdb_votes,story,summary,tagline,actors,wins_nominations,release_date
1626,Sabse Bada Sukh,tt0069204,NaN,https://en.wikipedia.org/wiki/Sabse_Bada_Sukh,Sabse Bada Sukh,Sabse Bada Sukh,0,2018,\N,Comedy|Drama,6.1,13,Village born Lalloo re-locates to Bombay and ...,Village born Lalloo re-locates to Bombay and ...,NaN,Vijay Arora|Asrani|Rajni Bala|Kumud Damle|Utpa...,NaN,NaN
1627,Daaka,tt10833860,https://upload.wikimedia.org/wikipedia/en/thum...,https://en.wikipedia.org/wiki/Daaka,Daaka,Daaka,0,2019,136,Action,7.4,38,Shinda tries robbing a bank so he can be wealt...,Shinda tries robbing a bank so he can be wealt...,NaN,Gippy Grewal|Zareen Khan|,NaN,1 November 2019 (USA)
1628,Humsafar,tt2403201,https://upload.wikimedia.org/wikipedia/en/thum...,https://en.wikipedia.org/wiki/Humsafar,Humsafar,Humsafar,0,2011,35,Drama|Romance,9.0,2968,Sara and Ashar are childhood friends who share...,Ashar and Khirad are forced to get married due...,NaN,Fawad Khan|,NaN,TV Series (2011–2012)

In [356]:
movies.iloc[2:4]

,title_x,imdb_id,poster_path,wiki_link,title_y,original_title,is_adult,year_of_release,runtime,genres,imdb_rating,imdb_votes,story,summary,tagline,actors,wins_nominations,release_date
2,The Accidental Prime Minister (film),tt6986710,https://upload.wikimedia.org/wikipedia/en/thum...,https://en.wikipedia.org/wiki/The_Accidental_P...,The Accidental Prime Minister,The Accidental Prime Minister,0,2019,112,Biography|Drama,6.1,5549,Based on the memoir by Indian policy analyst S...,Explores Manmohan Singh's tenure as the Prime ...,NaN,Anupam Kher|Akshaye Khanna|Aahana Kumra|Atul S...,NaN,11 January 2019 (USA)
3,Why Cheat India,tt8108208,https://upload.wikimedia.org/wikipedia/en/thum...,https://en.wikipedia.org/wiki/Why_Cheat_India,Why Cheat India,Why Cheat India,0,2019,121,Crime|Drama,6.0,1891,The movie focuses on existing malpractices in ...,The movie focuses on existing malpractices in ...,NaN,Emraan Hashmi|Shreya Dhanwanthary|Snighdadeep ...,NaN,18 January 2019 (USA)

<br>

### **Selecting rows by fancy indexing**

We can access any row with the help of fancy indexing.

In [357]:
movies.iloc[[0, 1]]

,title_x,imdb_id,poster_path,wiki_link,title_y,original_title,is_adult,year_of_release,runtime,genres,imdb_rating,imdb_votes,story,summary,tagline,actors,wins_nominations,release_date
0,Uri: The Surgical Strike,tt8291224,https://upload.wikimedia.org/wikipedia/en/thum...,https://en.wikipedia.org/wiki/Uri:_The_Surgica...,Uri: The Surgical Strike,Uri: The Surgical Strike,0,2019,138,Action|Drama|War,8.4,35112,Divided over five chapters the film chronicle...,Indian army special forces execute a covert op...,NaN,Vicky Kaushal|Paresh Rawal|Mohit Raina|Yami Ga...,4 wins,11 January 2019 (USA)
1,Battalion 609,tt9472208,NaN,https://en.wikipedia.org/wiki/Battalion_609,Battalion 609,Battalion 609,0,2019,131,War,4.1,73,The story revolves around a cricket match betw...,The story of Battalion 609 revolves around a c...,NaN,Vicky Ahuja|Shoaib Ibrahim|Shrikant Kamat|Elen...,NaN,11 January 2019 (India)

In [358]:
movies.iloc[[3, 4, 5]]

,title_x,imdb_id,poster_path,wiki_link,title_y,original_title,is_adult,year_of_release,runtime,genres,imdb_rating,imdb_votes,story,summary,tagline,actors,wins_nominations,release_date
3,Why Cheat India,tt8108208,https://upload.wikimedia.org/wikipedia/en/thum...,https://en.wikipedia.org/wiki/Why_Cheat_India,Why Cheat India,Why Cheat India,0,2019,121,Crime|Drama,6.0,1891,The movie focuses on existing malpractices in ...,The movie focuses on existing malpractices in ...,NaN,Emraan Hashmi|Shreya Dhanwanthary|Snighdadeep ...,NaN,18 January 2019 (USA)
4,Evening Shadows,tt6028796,NaN,https://en.wikipedia.org/wiki/Evening_Shadows,Evening Shadows,Evening Shadows,0,2018,102,Drama,7.3,280,While gay rights and marriage equality has bee...,Under the 'Evening Shadows' truth often plays...,NaN,Mona Ambegaonkar|Ananth Narayan Mahadevan|Deva...,17 wins & 1 nomination,11 January 2019 (India)
5,Soni (film),tt6078866,https://upload.wikimedia.org/wikipedia/en/thum...,https://en.wikipedia.org/wiki/Soni_(film),Soni,Soni,0,2018,97,Drama,7.2,1595,Soni a young policewoman in Delhi and her su...,While fighting crimes against women in Delhi ...,NaN,Geetika Vidya Ohlyan|Saloni Batra|Vikas Shukla...,3 wins & 5 nominations,18 January 2019 (USA)

In [359]:
movies.iloc[[0]]

,title_x,imdb_id,poster_path,wiki_link,title_y,original_title,is_adult,year_of_release,runtime,genres,imdb_rating,imdb_votes,story,summary,tagline,actors,wins_nominations,release_date
0,Uri: The Surgical Strike,tt8291224,https://upload.wikimedia.org/wikipedia/en/thum...,https://en.wikipedia.org/wiki/Uri:_The_Surgica...,Uri: The Surgical Strike,Uri: The Surgical Strike,0,2019,138,Action|Drama|War,8.4,35112,Divided over five chapters the film chronicle...,Indian army special forces execute a covert op...,NaN,Vicky Kaushal|Paresh Rawal|Mohit Raina|Yami Ga...,4 wins,11 January 2019 (USA)

<br>

### **Selecting by label**

We can select any row with by indexing, slicing  and fancy indexing with its label

In [360]:
ipl2 = ipl.set_index("ID")    # actually i make a dataframe ipl2 whose index is label so we can access it with label and also its index as it has default hidden index which start from zero and end on the end row postion
ipl2.head(2)

,City,Date,Season,MatchNumber,Team1,Team2,Venue,TossWinner,TossDecision,SuperOver,WinningTeam,WonBy,Margin,method,Player_of_Match,Team1Players,Team2Players,Umpire1,Umpire2
ID,,,,,,,,,,,,,,,,,,,
1312200,Ahmedabad,2022-05-29,2022,Final,Rajasthan Royals,Gujarat Titans,"Narendra Modi Stadium, Ahmedabad",Rajasthan Royals,bat,N,Gujarat Titans,Wickets,7.0,NaN,HH Pandya,"['YBK Jaiswal', 'JC Buttler', 'SV Samson', 'D ...","['WP Saha', 'Shubman Gill', 'MS Wade', 'HH Pan...",CB Gaffaney,Nitin Menon
1312199,Ahmedabad,2022-05-27,2022,Qualifier 2,Royal Challengers Bangalore,Rajasthan Royals,"Narendra Modi Stadium, Ahmedabad",Rajasthan Royals,field,N,Rajasthan Royals,Wickets,7.0,NaN,JC Buttler,"['V Kohli', 'F du Plessis', 'RM Patidar', 'GJ ...","['YBK Jaiswal', 'JC Buttler', 'SV Samson', 'D ...",CB Gaffaney,Nitin Menon

In [361]:
ipl2.loc[1312200]

City                                                       Ahmedabad
Date                                                      2022-05-29
Season                                                          2022
MatchNumber                                                    Final
Team1                                               Rajasthan Royals
Team2                                                 Gujarat Titans
Venue                               Narendra Modi Stadium, Ahmedabad
TossWinner                                          Rajasthan Royals
TossDecision                                                     bat
SuperOver                                                          N
WinningTeam                                           Gujarat Titans
WonBy                                                        Wickets
Margin                                                           7.0
method                                                           NaN
Player_of_Match                                            HH Pandya
Team1Players       ['YBK Jaiswal', 'JC Buttler', 'SV Samson', 'D ...
Team2Players       ['WP Saha', 'Shubman Gill', 'MS Wade', 'HH Pan...
Umpire1                                                  CB Gaffaney
Umpire2                                                  Nitin Menon
Name: 1312200, dtype: object

In [362]:
ipl2.loc[1312200:1312197]     # both included

,City,Date,Season,MatchNumber,Team1,Team2,Venue,TossWinner,TossDecision,SuperOver,WinningTeam,WonBy,Margin,method,Player_of_Match,Team1Players,Team2Players,Umpire1,Umpire2
ID,,,,,,,,,,,,,,,,,,,
1312200,Ahmedabad,2022-05-29,2022,Final,Rajasthan Royals,Gujarat Titans,"Narendra Modi Stadium, Ahmedabad",Rajasthan Royals,bat,N,Gujarat Titans,Wickets,7.0,NaN,HH Pandya,"['YBK Jaiswal', 'JC Buttler', 'SV Samson', 'D ...","['WP Saha', 'Shubman Gill', 'MS Wade', 'HH Pan...",CB Gaffaney,Nitin Menon
1312199,Ahmedabad,2022-05-27,2022,Qualifier 2,Royal Challengers Bangalore,Rajasthan Royals,"Narendra Modi Stadium, Ahmedabad",Rajasthan Royals,field,N,Rajasthan Royals,Wickets,7.0,NaN,JC Buttler,"['V Kohli', 'F du Plessis', 'RM Patidar', 'GJ ...","['YBK Jaiswal', 'JC Buttler', 'SV Samson', 'D ...",CB Gaffaney,Nitin Menon
1312198,Kolkata,2022-05-25,2022,Eliminator,Royal Challengers Bangalore,Lucknow Super Giants,"Eden Gardens, Kolkata",Lucknow Super Giants,field,N,Royal Challengers Bangalore,Runs,14.0,NaN,RM Patidar,"['V Kohli', 'F du Plessis', 'RM Patidar', 'GJ ...","['Q de Kock', 'KL Rahul', 'M Vohra', 'DJ Hooda...",J Madanagopal,MA Gough
1312197,Kolkata,2022-05-24,2022,Qualifier 1,Rajasthan Royals,Gujarat Titans,"Eden Gardens, Kolkata",Gujarat Titans,field,N,Gujarat Titans,Wickets,7.0,NaN,DA Miller,"['YBK Jaiswal', 'JC Buttler', 'SV Samson', 'D ...","['WP Saha', 'Shubman Gill', 'MS Wade', 'HH Pan...",BNJ Oxenford,VK Sharma

In [363]:
ipl2.loc[[1312200,1312197]]

,City,Date,Season,MatchNumber,Team1,Team2,Venue,TossWinner,TossDecision,SuperOver,WinningTeam,WonBy,Margin,method,Player_of_Match,Team1Players,Team2Players,Umpire1,Umpire2
ID,,,,,,,,,,,,,,,,,,,
1312200,Ahmedabad,2022-05-29,2022,Final,Rajasthan Royals,Gujarat Titans,"Narendra Modi Stadium, Ahmedabad",Rajasthan Royals,bat,N,Gujarat Titans,Wickets,7.0,NaN,HH Pandya,"['YBK Jaiswal', 'JC Buttler', 'SV Samson', 'D ...","['WP Saha', 'Shubman Gill', 'MS Wade', 'HH Pan...",CB Gaffaney,Nitin Menon
1312197,Kolkata,2022-05-24,2022,Qualifier 1,Rajasthan Royals,Gujarat Titans,"Eden Gardens, Kolkata",Gujarat Titans,field,N,Gujarat Titans,Wickets,7.0,NaN,DA Miller,"['YBK Jaiswal', 'JC Buttler', 'SV Samson', 'D ...","['WP Saha', 'Shubman Gill', 'MS Wade', 'HH Pan...",BNJ Oxenford,VK Sharma

<br>

# **Selecting Row & Column**
We can select both row and column

df[row, column]

In [364]:
ipl.iloc[1,1]        # it return the first row and first column value

'Ahmedabad'

In [365]:
ipl.iloc[0, 3]

'2022'

In [366]:
ipl.iloc[0:2, 4]

0          Final
1    Qualifier 2
Name: MatchNumber, dtype: str

In [367]:
ipl.iloc[0:3, 2:4]

         Date Season
0  2022-05-29   2022
1  2022-05-27   2022
2  2022-05-25   2022

In [368]:
ipl.iloc[[1, 2, 3], [2, 3]]   # by fancy indexing

         Date Season
1  2022-05-27   2022
2  2022-05-25   2022
3  2022-05-24   2022

In [369]:
ipl.head(1)

,ID,City,Date,Season,MatchNumber,Team1,Team2,Venue,TossWinner,TossDecision,SuperOver,WinningTeam,WonBy,Margin,method,Player_of_Match,Team1Players,Team2Players,Umpire1,Umpire2
0,1312200,Ahmedabad,2022-05-29,2022,Final,Rajasthan Royals,Gujarat Titans,"Narendra Modi Stadium, Ahmedabad",Rajasthan Royals,bat,N,Gujarat Titans,Wickets,7.0,NaN,HH Pandya,"['YBK Jaiswal', 'JC Buttler', 'SV Samson', 'D ...","['WP Saha', 'Shubman Gill', 'MS Wade', 'HH Pan...",CB Gaffaney,Nitin Menon

In [370]:
ipl.loc[0:2, 'City':'MatchNumber']   # here we are accessing the rows and columns with its label.

        City        Date Season  MatchNumber
0  Ahmedabad  2022-05-29   2022        Final
1  Ahmedabad  2022-05-27   2022  Qualifier 2
2    Kolkata  2022-05-25   2022   Eliminator

<br>

# **Filtering DataFrame**
We can also filter dataframe by applying relational and logical operation on the series of dataframe and it will give a bolean datatype series and we can use that as a mask with bolean indexing on the dataframe to actally see the original values.

In [371]:
mask = ipl["City"] == "Ahmedabad"     # it return a seris of bolean datatype and can use it as a mask with dataframe as a bolean indexing
ipl[mask] # it will give only the rows where the mask condition satisfied

,ID,City,Date,Season,MatchNumber,Team1,Team2,Venue,TossWinner,TossDecision,SuperOver,WinningTeam,WonBy,Margin,method,Player_of_Match,Team1Players,Team2Players,Umpire1,Umpire2
0,1312200,Ahmedabad,2022-05-29,2022,Final,Rajasthan Royals,Gujarat Titans,"Narendra Modi Stadium, Ahmedabad",Rajasthan Royals,bat,N,Gujarat Titans,Wickets,7.0,NaN,HH Pandya,"['YBK Jaiswal', 'JC Buttler', 'SV Samson', 'D ...","['WP Saha', 'Shubman Gill', 'MS Wade', 'HH Pan...",CB Gaffaney,Nitin Menon
1,1312199,Ahmedabad,2022-05-27,2022,Qualifier 2,Royal Challengers Bangalore,Rajasthan Royals,"Narendra Modi Stadium, Ahmedabad",Rajasthan Royals,field,N,Rajasthan Royals,Wickets,7.0,NaN,JC Buttler,"['V Kohli', 'F du Plessis', 'RM Patidar', 'GJ ...","['YBK Jaiswal', 'JC Buttler', 'SV Samson', 'D ...",CB Gaffaney,Nitin Menon
105,1254086,Ahmedabad,2021-05-02,2021,29,Punjab Kings,Delhi Capitals,"Narendra Modi Stadium, Ahmedabad",Delhi Capitals,field,N,Delhi Capitals,Wickets,7.0,NaN,MA Agarwal,"['P Simran Singh', 'MA Agarwal', 'CH Gayle', '...","['PP Shaw', 'S Dhawan', 'SPD Smith', 'RR Pant'...",AK Chaudhary,AY Dandekar
108,1254083,Ahmedabad,2021-04-30,2021,26,Punjab Kings,Royal Challengers Bangalore,"Narendra Modi Stadium, Ahmedabad",Royal Challengers Bangalore,field,N,Punjab Kings,Runs,34.0,NaN,Harpreet Brar,"['KL Rahul', 'P Simran Singh', 'CH Gayle', 'N ...","['V Kohli', 'D Padikkal', 'RM Patidar', 'GJ Ma...",S Ravi,VK Sharma
109,1254082,Ahmedabad,2021-04-29,2021,25,Kolkata Knight Riders,Delhi Capitals,"Narendra Modi Stadium, Ahmedabad",Delhi Capitals,field,N,Delhi Capitals,Wickets,7.0,NaN,PP Shaw,"['N Rana', 'Shubman Gill', 'RA Tripathi', 'EJG...","['PP Shaw', 'S Dhawan', 'RR Pant', 'MP Stoinis...",AK Chaudhary,YC Barde
112,1254079,Ahmedabad,2021-04-27,2021,22,Royal Challengers Bangalore,Delhi Capitals,"Narendra Modi Stadium, Ahmedabad",Delhi Capitals,field,N,Royal Challengers Bangalore,Runs,1.0,NaN,AB de Villiers,"['V Kohli', 'D Padikkal', 'RM Patidar', 'GJ Ma...","['PP Shaw', 'S Dhawan', 'SPD Smith', 'RR Pant'...",S Ravi,VK Sharma
113,1254078,Ahmedabad,2021-04-26,2021,21,Punjab Kings,Kolkata Knight Riders,"Narendra Modi Stadium, Ahmedabad",Kolkata Knight Riders,field,N,Kolkata Knight Riders,Wickets,5.0,NaN,EJG Morgan,"['KL Rahul', 'MA Agarwal', 'CH Gayle', 'DJ Hoo...","['Shubman Gill', 'N Rana', 'RA Tripathi', 'SP ...",PR Reiffel,YC Barde
470,829749,Ahmedabad,2015-04-24,2015,22,Rajasthan Royals,Royal Challengers Bangalore,"Sardar Patel Stadium, Motera",Royal Challengers Bangalore,field,N,Royal Challengers Bangalore,Wickets,9.0,NaN,MA Starc,"['AM Rahane', 'SR Watson', 'SPD Smith', 'KK Na...","['CH Gayle', 'V Kohli', 'AB de Villiers', 'Man...",M Erasmus,S Ravi
474,829741,Ahmedabad,2015-04-21,2015,18,Rajasthan Royals,Kings XI Punjab,"Sardar Patel Stadium, Motera",Kings XI Punjab,field,Y,Kings XI Punjab,SuperOver,NaN,NaN,SE Marsh,"['AM Rahane', 'SR Watson', 'DJ Hooda', 'SPD Sm...","['M Vijay', 'V Sehwag', 'SE Marsh', 'GJ Maxwel...",M Erasmus,S Ravi
476,829735,Ahmedabad,2015-04-19,2015,15,Rajasthan Royals,Chennai Super Kings,"Sardar Patel Stadium, Motera",Chennai Super Kings,bat,N,Rajasthan Royals,Wickets,8.0,NaN,AM Rahane,"['AM Rahane', 'SR Watson', 'SPD Smith', 'KK Na...","['DR Smith', 'BB McCullum', 'SK Raina', 'F du ...",AK Chaudhary,M Erasmus
483,829721,Ahmedabad,2015-04-14,2015,9,Rajasthan Royals,Mumbai Indians,"Sardar Patel Stadium, Motera",Mumbai Indians,bat,N,Rajasthan Royals,Wickets,7.0,NaN,SPD Smith,"['AM Rahane', 'SV Samson', 'SPD Smith', 'DJ Ho...","['AJ Finch', 'PA Patel', 'UBT Chand', 'RG Shar...",AK Chaudhary,SD Fry
508,734017,Ahmedabad,2014-05-19,2014,44,Rajasthan Royals,Mumbai Indians,"Sardar Patel Stadium, Motera",Mumbai Indians,bat,N,Mumbai Indians,Runs,25.0,NaN,MEK Hussey,"['KK Nair', 'UBT Chand', 'SR Watson', 'SV Sams...","['MEK Hussey', 'LMP Simmons', 'KA Pollard', 'R...",S Ravi,RJ Tucker
511,734011,Ahmedabad,2014-05-15,2014,41,Rajasthan Royals,Delhi Daredevils,"Sardar Patel Stadium, Motera",Delhi Daredevils,field,N,Rajasthan Royals,Runs,62.0,NaN,AM Rahane,"['AM Rahane', 'KK Nair', 'KK Cooper', 'SV Sams...","['KP Pietersen', 'MA Agarwal', 'KD Karthik', '...",S Ravi,RJ Tucker
522,733989,Ahmedabad,2014-05-08,2014,30,Rajasthan Royals,Sunrisers Hyderabad,"Sardar Patel Stadium, Motera",Rajasthan Royals,field,N,Sunrisers Hyderabad,Runs,32.0,NaN,B Kumar,"['AM Rahane', 'KK Nair', 'SV Samson', 'SR Wats...","['S Dhawan', 'AJ Finch', 'KL Rahul', 'NV Ojha'...",AK Chaudhary,NJ Llong
527,733979,Ahmedabad,2014-05-05,2014,25,Rajasthan Royals,Kolkata Knight Riders,"Sardar Patel Stadium, Motera",Kolkata Knight Riders,field,N,Rajasthan Royals,Runs,10.0,NaN,PV Tambe,"['AM Rahane', 'KK Nair', 'SV Samson', 'SR Wats...","['RV Uthappa', 'G Gambhir', 'AD Russell', 'MK ...",NJ Llong,CK Nandan
811,419129,Ahmedabad,2010-03-28,2009/10,24,Rajasthan Royals,Chennai Super Kings,"Sardar Patel Stadium, Motera",Rajasthan Royals,bat,N,Rajasthan Royals,Runs,17.0,NaN,NV Ojha,"['MJ Lumb', 'NV Ojha', 'FY Fazal', 'YK Pathan'...","['M Vijay', 'ML Hayden', 'SK Raina', 'MS Dhoni...",SS Hazare,SJA Taufel
813,419126,Ahmedabad,2010-03-26,2009/10,22,Rajasthan Royals,Deccan Chargers,"Sardar Patel Stadium, Motera",Deccan Chargers,bat,N,Rajasthan Royals,Wickets,8.0,NaN,YK Pathan,"['MJ Lumb', 'NV Ojha', 'YK Pathan', 'FY Fazal'...","['AC Gilchrist', 'VVS Laxman', 'HH Gibbs', 'A ...",HDPK Dharmasena,SJA Taufel
822,419118,Ahmedabad,2010-03-20,2009/10,13,Rajasthan Royals,Kolkata Knight Riders,"Sardar Patel Stadium, Motera",Rajasthan Royals,bat,N,Rajasthan Royals,Runs,34.0,NaN,AA Jhunjhunwala,"['MJ Lumb', 'NV Ojha', 'FY Fazal', 'AA Jhunjhu...","['MK Tiwary', 'BJ Hodge', 'CA Pujara', 'SC Gan...",RE Koertzen,RB Tiffin
829,419111,Ahmedabad,2010-03-15,2009/10,6,Rajasthan Royals,Delhi Daredevils,"Sardar Patel Stadium, Motera",Delhi Daredevils,field,N,Delhi Daredevils,Wickets,6.0,NaN,V Sehwag,"['SA Asnodkar', 'GC Smith', 'NV Ojha', 'YK Pat...","['G Gambhir', 'V Sehwag', 'TM Dilshan', 'AB de...",BG Jerling,RE Koertzen

<br>

#### **We will do some filtering question on this so you will better understand it.**

<br>

### **1. find all the final winners**

In [372]:
final_winner = ipl[ipl['MatchNumber']=="Final"]

final_winner[["Team1", "Team2", "WinningTeam", "Season"]]

,Team1,Team2,WinningTeam,Season
0,Rajasthan Royals,Gujarat Titans,Gujarat Titans,2022
74,Chennai Super Kings,Kolkata Knight Riders,Chennai Super Kings,2021
134,Delhi Capitals,Mumbai Indians,Mumbai Indians,2020/21
194,Mumbai Indians,Chennai Super Kings,Mumbai Indians,2019
254,Sunrisers Hyderabad,Chennai Super Kings,Chennai Super Kings,2018
314,Mumbai Indians,Rising Pune Supergiant,Mumbai Indians,2017
373,Royal Challengers Bangalore,Sunrisers Hyderabad,Sunrisers Hyderabad,2016
433,Mumbai Indians,Chennai Super Kings,Mumbai Indians,2015
492,Kolkata Knight Riders,Kings XI Punjab,Kolkata Knight Riders,2014
552,Chennai Super Kings,Mumbai Indians,Mumbai Indians,2013
628,Kolkata Knight Riders,Chennai Super Kings,Kolkata Knight Riders,2012
702,Chennai Super Kings,Royal Challengers Bangalore,Chennai Super Kings,2011
775,Chennai Super Kings,Mumbai Indians,Chennai Super Kings,2009/10
835,Royal Challengers Bangalore,Deccan Chargers,Deccan Chargers,2009
892,Chennai Super Kings,Rajasthan Royals,Rajasthan Royals,2007/08

<br>

### **2. how many super over finishes have occured**

In [373]:
ipl[ipl["SuperOver"]=="Y"].shape[0]

14

<br>

### **3. how many matches has csk won in kolkata**

In [374]:
ipl[(ipl["City"]=="Kolkata") & (ipl["WinningTeam"]=="Chennai Super Kings")].shape[0]

5

<br>

### **4. toss winner is match winner in percentage**

In [375]:
(ipl[ipl["TossWinner"]==ipl["WinningTeam"]].shape[0]/ipl.shape[0])*100

51.473684210526315

<br>

### **5. movies with rating higher than 8 and votes>10000**

In [376]:
movies[(movies["imdb_rating"]>8) & (movies["imdb_votes"]>10000)].shape[0]

43

<br>

### **6. Action movies with rating higher than 7.5**

In [377]:
movies[(movies["genres"].str.contains("Action")) & (movies["imdb_rating"]>7.5)].shape[0]

33

<br>

# **Adding new columns**

In [378]:
movies.head(2)

,title_x,imdb_id,poster_path,wiki_link,title_y,original_title,is_adult,year_of_release,runtime,genres,imdb_rating,imdb_votes,story,summary,tagline,actors,wins_nominations,release_date
0,Uri: The Surgical Strike,tt8291224,https://upload.wikimedia.org/wikipedia/en/thum...,https://en.wikipedia.org/wiki/Uri:_The_Surgica...,Uri: The Surgical Strike,Uri: The Surgical Strike,0,2019,138,Action|Drama|War,8.4,35112,Divided over five chapters the film chronicle...,Indian army special forces execute a covert op...,NaN,Vicky Kaushal|Paresh Rawal|Mohit Raina|Yami Ga...,4 wins,11 January 2019 (USA)
1,Battalion 609,tt9472208,NaN,https://en.wikipedia.org/wiki/Battalion_609,Battalion 609,Battalion 609,0,2019,131,War,4.1,73,The story revolves around a cricket match betw...,The story of Battalion 609 revolves around a c...,NaN,Vicky Ahuja|Shoaib Ibrahim|Shrikant Kamat|Elen...,NaN,11 January 2019 (India)

In [379]:
movies["dummy"] = 100     # it will add column dummy having each row 100

In [380]:
movies.head(2)

,title_x,imdb_id,poster_path,wiki_link,title_y,original_title,is_adult,year_of_release,runtime,genres,imdb_rating,imdb_votes,story,summary,tagline,actors,wins_nominations,release_date,dummy
0,Uri: The Surgical Strike,tt8291224,https://upload.wikimedia.org/wikipedia/en/thum...,https://en.wikipedia.org/wiki/Uri:_The_Surgica...,Uri: The Surgical Strike,Uri: The Surgical Strike,0,2019,138,Action|Drama|War,8.4,35112,Divided over five chapters the film chronicle...,Indian army special forces execute a covert op...,NaN,Vicky Kaushal|Paresh Rawal|Mohit Raina|Yami Ga...,4 wins,11 January 2019 (USA),100
1,Battalion 609,tt9472208,NaN,https://en.wikipedia.org/wiki/Battalion_609,Battalion 609,Battalion 609,0,2019,131,War,4.1,73,The story revolves around a cricket match betw...,The story of Battalion 609 revolves around a c...,NaN,Vicky Ahuja|Shoaib Ibrahim|Shrikant Kamat|Elen...,NaN,11 January 2019 (India),100

In [381]:
movies["actors"]

0       Vicky Kaushal|Paresh Rawal|Mohit Raina|Yami Ga...
1       Vicky Ahuja|Shoaib Ibrahim|Shrikant Kamat|Elen...
2       Anupam Kher|Akshaye Khanna|Aahana Kumra|Atul S...
3       Emraan Hashmi|Shreya Dhanwanthary|Snighdadeep ...
4       Mona Ambegaonkar|Ananth Narayan Mahadevan|Deva...
                              ...
1624    Ajay Devgn|Sonali Bendre|Namrata Shirodkar|Pre...
1625    Ameesha Patel|Jimmy Sheirgill|Nafisa Ali|Gulsh...
1626    Vijay Arora|Asrani|Rajni Bala|Kumud Damle|Utpa...
1627                            Gippy Grewal|Zareen Khan|
1628                                          Fawad Khan|
Name: actors, Length: 1629, dtype: str

In [382]:
movies["lead"] = movies["actors"].str.split("|").str[0]

In [383]:
movies.head(3)

,title_x,imdb_id,poster_path,wiki_link,title_y,original_title,is_adult,year_of_release,runtime,genres,imdb_rating,imdb_votes,story,summary,tagline,actors,wins_nominations,release_date,dummy,lead
0,Uri: The Surgical Strike,tt8291224,https://upload.wikimedia.org/wikipedia/en/thum...,https://en.wikipedia.org/wiki/Uri:_The_Surgica...,Uri: The Surgical Strike,Uri: The Surgical Strike,0,2019,138,Action|Drama|War,8.4,35112,Divided over five chapters the film chronicle...,Indian army special forces execute a covert op...,NaN,Vicky Kaushal|Paresh Rawal|Mohit Raina|Yami Ga...,4 wins,11 January 2019 (USA),100,Vicky Kaushal
1,Battalion 609,tt9472208,NaN,https://en.wikipedia.org/wiki/Battalion_609,Battalion 609,Battalion 609,0,2019,131,War,4.1,73,The story revolves around a cricket match betw...,The story of Battalion 609 revolves around a c...,NaN,Vicky Ahuja|Shoaib Ibrahim|Shrikant Kamat|Elen...,NaN,11 January 2019 (India),100,Vicky Ahuja
2,The Accidental Prime Minister (film),tt6986710,https://upload.wikimedia.org/wikipedia/en/thum...,https://en.wikipedia.org/wiki/The_Accidental_P...,The Accidental Prime Minister,The Accidental Prime Minister,0,2019,112,Biography|Drama,6.1,5549,Based on the memoir by Indian policy analyst S...,Explores Manmohan Singh's tenure as the Prime ...,NaN,Anupam Kher|Akshaye Khanna|Aahana Kumra|Atul S...,NaN,11 January 2019 (USA),100,Anupam Kher


<br>

<br>

# **How to reduce the memory usage of dataframe**
We can reduce the memory usage of any dataframe by change its datatype.

In [384]:
movies.head(2)

,title_x,imdb_id,poster_path,wiki_link,title_y,original_title,is_adult,year_of_release,runtime,genres,imdb_rating,imdb_votes,story,summary,tagline,actors,wins_nominations,release_date,dummy,lead
0,Uri: The Surgical Strike,tt8291224,https://upload.wikimedia.org/wikipedia/en/thum...,https://en.wikipedia.org/wiki/Uri:_The_Surgica...,Uri: The Surgical Strike,Uri: The Surgical Strike,0,2019,138,Action|Drama|War,8.4,35112,Divided over five chapters the film chronicle...,Indian army special forces execute a covert op...,NaN,Vicky Kaushal|Paresh Rawal|Mohit Raina|Yami Ga...,4 wins,11 January 2019 (USA),100,Vicky Kaushal
1,Battalion 609,tt9472208,NaN,https://en.wikipedia.org/wiki/Battalion_609,Battalion 609,Battalion 609,0,2019,131,War,4.1,73,The story revolves around a cricket match betw...,The story of Battalion 609 revolves around a c...,NaN,Vicky Ahuja|Shoaib Ibrahim|Shrikant Kamat|Elen...,NaN,11 January 2019 (India),100,Vicky Ahuja

In [385]:
movies.info()    # now check the memory usage it use 2.0 + MB so we have to reduce it

<class 'pandas.DataFrame'>
RangeIndex: 1629 entries, 0 to 1628
Data columns (total 20 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   title_x           1629 non-null   str
 1   imdb_id           1629 non-null   str
 2   poster_path       1526 non-null   str
 3   wiki_link         1629 non-null   str
 4   title_y           1629 non-null   str
 5   original_title    1629 non-null   str
 6   is_adult          1629 non-null   int64
 7   year_of_release   1629 non-null   int64
 8   runtime           1629 non-null   str
 9   genres            1629 non-null   str
 10  imdb_rating       1629 non-null   float64
 11  imdb_votes        1629 non-null   int64
 12  story             1609 non-null   str
 13  summary           1629 non-null   str
 14  tagline           557 non-null    str
 15  actors            1624 non-null   str
 16  wins_nominations  707 non-null    str
 17  release_date      1522 non-null   str
 18  dummy             1629 non-null   int64
 19  lead              1624 non-null   object
dtypes: float64(1), int64(4), object(1), str(14)
memory usage: 2.0+ MB

**Look in the above info carefully :**

- The memory usage is 2.0+ MB
  
- `imdb_rating`  datatye is float64 which use high memory so we have to convert it into float32 because float32 is made for less range digits and use less memory.
  
- `is_adult` & `year_of_release` have datatypes int64 and we know this both are act like a category datatypes because 0 and 1 repeated in the `is_adult` and years repeated in `year_of_release` so we can convert it into category datatype to reduce the memory

- In the same way we can change some other datatypes to reduce its memory usage.

In [386]:
movies['imdb_rating'] = movies['imdb_rating'].astype('Float32')

In [387]:
movies.info()

<class 'pandas.DataFrame'>
RangeIndex: 1629 entries, 0 to 1628
Data columns (total 20 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   title_x           1629 non-null   str
 1   imdb_id           1629 non-null   str
 2   poster_path       1526 non-null   str
 3   wiki_link         1629 non-null   str
 4   title_y           1629 non-null   str
 5   original_title    1629 non-null   str
 6   is_adult          1629 non-null   int64
 7   year_of_release   1629 non-null   int64
 8   runtime           1629 non-null   str
 9   genres            1629 non-null   str
 10  imdb_rating       1629 non-null   Float32
 11  imdb_votes        1629 non-null   int64
 12  story             1609 non-null   str
 13  summary           1629 non-null   str
 14  tagline           557 non-null    str
 15  actors            1624 non-null   str
 16  wins_nominations  707 non-null    str
 17  release_date      1522 non-null   str
 18  dummy             1629 non-null   int64
 19  lead              1624 non-null   object
dtypes: Float32(1), int64(4), object(1), str(14)
memory usage: 2.0+ MB

In [388]:
movies[["year_of_release", "is_adult"]] = movies[["year_of_release", "is_adult"]].astype("category")

In [389]:
movies.info()

<class 'pandas.DataFrame'>
RangeIndex: 1629 entries, 0 to 1628
Data columns (total 20 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   title_x           1629 non-null   str
 1   imdb_id           1629 non-null   str
 2   poster_path       1526 non-null   str
 3   wiki_link         1629 non-null   str
 4   title_y           1629 non-null   str
 5   original_title    1629 non-null   str
 6   is_adult          1629 non-null   category
 7   year_of_release   1629 non-null   category
 8   runtime           1629 non-null   str
 9   genres            1629 non-null   str
 10  imdb_rating       1629 non-null   Float32
 11  imdb_votes        1629 non-null   int64
 12  story             1609 non-null   str
 13  summary           1629 non-null   str
 14  tagline           557 non-null    str
 15  actors            1624 non-null   str
 16  wins_nominations  707 non-null    str
 17  release_date      1522 non-null   str
 18  dummy             1629 non-null   int64
 19  lead              1624 non-null   object
dtypes: Float32(1), category(2), int64(2), object(1), str(14)
memory usage: 2.0+ MB

### **Notice here the + sign from 2.0 + MB remove and it convert to 2.0 MB**
It means that the memory of dataframe is reducing. Actully the movies dataframe is to much big and we cannot see the difference as it is in MB

<br>

### **So i have another dataframe which is in KB and apply the same method so that i show the clear difference to you people.**

In [390]:
ipl.info()

<class 'pandas.DataFrame'>
RangeIndex: 950 entries, 0 to 949
Data columns (total 20 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   ID               950 non-null    int64
 1   City             899 non-null    str
 2   Date             950 non-null    str
 3   Season           950 non-null    str
 4   MatchNumber      950 non-null    str
 5   Team1            950 non-null    str
 6   Team2            950 non-null    str
 7   Venue            950 non-null    str
 8   TossWinner       950 non-null    str
 9   TossDecision     950 non-null    str
 10  SuperOver        946 non-null    str
 11  WinningTeam      946 non-null    str
 12  WonBy            950 non-null    str
 13  Margin           932 non-null    float64
 14  method           19 non-null     str
 15  Player_of_Match  946 non-null    str
 16  Team1Players     950 non-null    str
 17  Team2Players     950 non-null    str
 18  Umpire1          950 non-null    str
 19  Umpire2          950 non-null    str
dtypes: float64(1), int64(1), str(18)
memory usage: 576.2 KB

In [391]:
ipl["Team1"]=ipl["Team1"].astype('category')
ipl.info()

<class 'pandas.DataFrame'>
RangeIndex: 950 entries, 0 to 949
Data columns (total 20 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   ID               950 non-null    int64
 1   City             899 non-null    str
 2   Date             950 non-null    str
 3   Season           950 non-null    str
 4   MatchNumber      950 non-null    str
 5   Team1            950 non-null    category
 6   Team2            950 non-null    str
 7   Venue            950 non-null    str
 8   TossWinner       950 non-null    str
 9   TossDecision     950 non-null    str
 10  SuperOver        946 non-null    str
 11  WinningTeam      946 non-null    str
 12  WonBy            950 non-null    str
 13  Margin           932 non-null    float64
 14  method           19 non-null     str
 15  Player_of_Match  946 non-null    str
 16  Team1Players     950 non-null    str
 17  Team2Players     950 non-null    str
 18  Umpire1          950 non-null    str
 19  Umpire2          950 non-null    str
dtypes: category(1), float64(1), int64(1), str(17)
memory usage: 553.4 KB

### **Now Look at the info before and after changing the datatype**

<br>

----