# Task for SQL DML session

Load this dataset in your database and perform below given tasks.

DataSet - https://docs.google.com/spreadsheets/d/e/2PACX-1vRa1wWwXmzxEvqITxj4OQTeLywlGTTsOTbhSRqKj2lPuGefjlci-DQhgLBPpgWXe8AAUu2WUBqY59X1/pub?gid=1030172542&single=true&output=csv

Look for data description

Kaggle - https://www.kaggle.com/datasets/thedevastator/insurance-claim-analysis-demographic-and-health?select=insurance_data.csv

In [16]:
import mysql.connector
import pandas as pd


con = mysql.connector.connect(
    host="localhost",
    password='',
    user='root',
    database='import_practice'
)

In [17]:
pd.read_sql_query("select * from insurance", con=con)

C:\Users\HP\AppData\Local\Temp\ipykernel_21616\1228278016.py:1: UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.
  pd.read_sql_query("select * from insurance", con=con)

,level_0,index,PatientID,age,gender,bmi,bloodpressure,diabetic,children,smoker,region,claim
0,0,0,1,39.0,male,23.2,91,Yes,0,No,southeast,1121.87
1,1,1,2,24.0,male,30.1,87,No,0,No,southeast,1131.51
2,2,2,3,NaN,male,33.3,82,Yes,0,No,southeast,1135.94
3,3,3,4,NaN,male,33.7,80,No,0,No,northwest,1136.40
4,4,4,5,NaN,male,34.1,100,No,0,No,northwest,1137.01
...,...,...,...,...,...,...,...,...,...,...,...,...
1335,1335,1335,1336,44.0,female,35.5,88,Yes,0,Yes,northwest,55135.40
1336,1336,1336,1337,59.0,female,38.1,120,No,1,Yes,northeast,58571.07
1337,1337,1337,1338,30.0,male,34.5,91,Yes,3,Yes,northwest,60021.40
1338,1338,1338,1339,37.0,male,30.4,106,No,0,Yes,southeast,62592.87
1339,1339,1339,1340,30.0,female,47.4,101,No,0,Yes,southeast,63770.43

### Perform the following queries

1. Show records of 'male' patient from 'southwest' region.

In [23]:
pd.read_sql_query("SELECT * FROM insurance where gender='male' AND region='southeast'", con=con)

C:\Users\HP\AppData\Local\Temp\ipykernel_21616\2902547677.py:1: UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.
  pd.read_sql_query("SELECT * FROM insurance where gender='male' AND region='southeast'", con=con)

,level_0,index,PatientID,age,gender,bmi,bloodpressure,diabetic,children,smoker,region,claim
0,0,0,1,39.0,male,23.2,91,Yes,0,No,southeast,1121.87
1,1,1,2,24.0,male,30.1,87,No,0,No,southeast,1131.51
2,2,2,3,NaN,male,33.3,82,Yes,0,No,southeast,1135.94
3,19,19,20,48.0,male,33.3,91,Yes,0,No,southeast,1391.53
4,20,20,21,45.0,male,23.2,85,Yes,0,No,southeast,1515.34
...,...,...,...,...,...,...,...,...,...,...,...,...
214,1327,1327,1328,49.0,male,40.9,107,No,0,Yes,southeast,48673.56
215,1328,1328,1329,45.0,male,42.1,117,No,1,Yes,southeast,48675.52
216,1331,1331,1332,18.0,male,41.1,104,No,1,Yes,southeast,48970.25
217,1332,1332,1333,26.0,male,37.0,120,No,2,Yes,southeast,49577.66
218,1338,1338,1339,37.0,male,30.4,106,No,0,Yes,southeast,62592.87

2. Show all records having bmi in range 30 to 45 both inclusive.

In [25]:
pd.read_sql_query("SELECT * FROM insurance where bmi BETWEEN 30 AND 45", con=con)

C:\Users\HP\AppData\Local\Temp\ipykernel_21616\3290698700.py:1: UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.
  pd.read_sql_query("SELECT * FROM insurance where bmi BETWEEN 30 AND 45", con=con)

,level_0,index,PatientID,age,gender,bmi,bloodpressure,diabetic,children,smoker,region,claim
0,1,1,2,24.0,male,30.1,87,No,0,No,southeast,1131.51
1,2,2,3,NaN,male,33.3,82,Yes,0,No,southeast,1135.94
2,3,3,4,NaN,male,33.7,80,No,0,No,northwest,1136.40
3,4,4,5,NaN,male,34.1,100,No,0,No,northwest,1137.01
4,5,5,6,NaN,male,34.4,96,Yes,0,No,northwest,1137.47
...,...,...,...,...,...,...,...,...,...,...,...,...
683,1334,1334,1335,43.0,male,32.8,125,No,0,Yes,southwest,52590.83
684,1335,1335,1336,44.0,female,35.5,88,Yes,0,Yes,northwest,55135.40
685,1336,1336,1337,59.0,female,38.1,120,No,1,Yes,northeast,58571.07
686,1337,1337,1338,30.0,male,34.5,91,Yes,3,Yes,northwest,60021.40
687,1338,1338,1339,37.0,male,30.4,106,No,0,Yes,southeast,62592.87



3. Show minimum and maximum bloodpressure of diabetic patient who smokes. Make column names as MinBP and MaxBP respectively.

In [28]:
pd.read_sql_query("SELECT MAX(bloodpressure) AS 'MaxBP', MIN(bloodpressure) AS 'MinBP' FROM insurance WHERE diabetic='Yes' AND smoker='Yes'", con=con)

C:\Users\HP\AppData\Local\Temp\ipykernel_21616\1139231126.py:1: UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.
  pd.read_sql_query("SELECT MAX(bloodpressure) AS 'MaxBP', MIN(bloodpressure) AS 'MinBP' FROM insurance WHERE diabetic='Yes' AND smoker='Yes'", con=con)

   MaxBP  MinBP
0    140     80

4. Find no of unique patients who are not from southwest region.

In [34]:
pd.read_sql_query("SELECT COUNT(DISTINCT(PatientID)) AS 'Patient' FROM insurance where region!='southwest'", con=con)

C:\Users\HP\AppData\Local\Temp\ipykernel_21616\1596945950.py:1: UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.
  pd.read_sql_query("SELECT COUNT(DISTINCT(PatientID)) AS 'Patient' FROM insurance where region!='southwest'", con=con)

   Patient
0     1023

5. Total claim amount from male smoker.

In [39]:
pd.read_sql_query("SELECT SUM(claim) AS 'Total_claim' FROM insurance WHERE smoker='Yes'", con=con)

C:\Users\HP\AppData\Local\Temp\ipykernel_21616\3798324637.py:1: UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.
  pd.read_sql_query("SELECT SUM(claim) AS 'Total_claim' FROM insurance WHERE smoker='Yes'", con=con)

   Total_claim
0   8781763.56


6. Select all records of south region.

In [40]:
pd.read_sql_query('SELECT * FROM insurance WHERE region LIKE "south%"', con=con)

C:\Users\HP\AppData\Local\Temp\ipykernel_21616\788289507.py:1: UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.
  pd.read_sql_query('SELECT * FROM insurance WHERE region LIKE "south%"', con=con)

,level_0,index,PatientID,age,gender,bmi,bloodpressure,diabetic,children,smoker,region,claim
0,0,0,1,39.0,male,23.2,91,Yes,0,No,southeast,1121.87
1,1,1,2,24.0,male,30.1,87,No,0,No,southeast,1131.51
2,2,2,3,NaN,male,33.3,82,Yes,0,No,southeast,1135.94
3,16,16,17,35.0,male,34.1,90,No,0,No,southwest,1261.44
4,17,17,18,41.0,male,34.4,84,No,0,No,southwest,1261.86
...,...,...,...,...,...,...,...,...,...,...,...,...
752,1332,1332,1333,26.0,male,37.0,120,No,2,Yes,southeast,49577.66
753,1333,1333,1334,44.0,male,36.4,127,No,1,Yes,southwest,51194.56
754,1334,1334,1335,43.0,male,32.8,125,No,0,Yes,southwest,52590.83
755,1338,1338,1339,37.0,male,30.4,106,No,0,Yes,southeast,62592.87
756,1339,1339,1340,30.0,female,47.4,101,No,0,Yes,southeast,63770.43

7. No of patient having normal blood pressure. Normal range[90-120]

In [49]:
pd.read_sql_query("SELECT COUNT(*) AS 'patient_no' FROM insurance WHERE bloodpressure BETWEEN 90 AND 120", con=con)

C:\Users\HP\AppData\Local\Temp\ipykernel_21616\2848214330.py:1: UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.
  pd.read_sql_query("SELECT COUNT(*) AS 'patient_no' FROM insurance WHERE bloodpressure BETWEEN 90 AND 120", con=con)

   patient_no
0         758

8. No of pateint belo 17 years of age having normal blood pressure as per below formula -
    - BP normal range = 80+(age in years × 2) to 100 + (age in years × 2)

    - Note: Formula taken just for practice, don't take in real sense.

In [56]:
pd.read_sql_query("SELECT COUNT(*) FROM insurance WHERE age < 17 AND bloodpressure >= 80 + (age * 2) AND bloodpressure <= 100 + (age * 2)", con=con)

C:\Users\HP\AppData\Local\Temp\ipykernel_21616\2680749248.py:1: UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.
  pd.read_sql_query("SELECT COUNT(*) FROM insurance WHERE age < 17 AND bloodpressure >= 80 + (age * 2) AND bloodpressure <= 100 + (age * 2)", con=con)

   COUNT(*)
0         0

9. What is the average claim amount for non-smoking female patients who are diabetic?

In [62]:
pd.read_sql_query("SELECT AVG(claim) AS 'avg_claim' FROM insurance WHERE smoker='No' AND gender='female' AND diabetic='Yes'", con=con)

C:\Users\HP\AppData\Local\Temp\ipykernel_21616\367356699.py:1: UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.
  pd.read_sql_query("SELECT AVG(claim) AS 'avg_claim' FROM insurance WHERE smoker='No' AND gender='female' AND diabetic='Yes'", con=con)

     avg_claim
0  8593.768631

10. Write a SQL query to update the claim amount for the patient with PatientID = 1234 to 5000.

In [ ]:

# update query does not work here it can work directly in mysql so you can run it there

# pd.read_sql_query("UPDATE insurance SET claim=5000 WHERE PatientID=1234", con=con)

11. Write a SQL query to delete all records for patients who are smokers and have no children.

In [ ]:
# DELET insurance WHERE smoker='Yes' AND children=0