In [ ]:
import pandas as pd
from sqlalchemy import create_engine


engine = create_engine("mysql+mysqldb://root:@localhost/import_practice")

try:
    pd.read_csv("athlete_events.csv").to_sql(name="athlete", con=engine, if_exists='append', index=False)
except Exception as e:
    print(e)

C:\Users\HP\AppData\Roaming\Python\Python313\site-packages\pandas\core\computation\expressions.py:22: UserWarning: Pandas requires version '2.10.2' or newer of 'numexpr' (version '2.10.1' currently installed).
  from pandas.core.computation.check import NUMEXPR_INSTALLED

271116

In [1]:
import mysql.connector

con = mysql.connector.connect(
    user="root",
    host="localhost",
    password="",
    database="import_practice")

# SQL SubQuery



## Problems 1-6


For problems 1 to 6, use the Olympic dataset. You can get that from [here](https://drive.google.com/file/d/1EGIRBkbQGByJPvCqDtxtTnXv93oGunFp/view?usp=share_link).


**Column description:**
1. ID -> ID of every records to our dataset. It has integer datatype.
2. Name -> Name of the athletes.
3. Sex -> Gender of the athletes.
4. Height -> Height of the athletes
5. Weight -> Weight of the athletes
6. NOC -> In which country, the athletes belong to. This is actually the country code.
7. Year -> In which year, the athlete has participated
8. Sport -> What is the sport name in which the athlete participated.
9. Event -> Event name of the sport
10. Medal -> Which medal the athlege got. If the athlete did not get any medal then this cell is blank.
11. country -> The name of the country.

### Problem 1

Display the names of athletes who won a gold medal in the 2008 Olympics and whose height is greater than the average height of all athletes in the 2008 Olympics.


### Problem 2

Display the names of athletes who won a medal in the sport of basketball in the 2016 Olympics and whose weight is less than the average weight of all athletes who won a medal in the 2016 Olympics.



### Problem 3

Display the names of all athletes who have won a medal in the sport of swimming in both the 2008 and 2016 Olympics.



### Problem 4

Display the names of all countries that have won more than 50 medals in a single year.



### Problem 5

Display the names of all athletes who have won medals in more than one sport in the same year.



### Problem 6

What is the average weight difference between male and female athletes in the Olympics who have won a medal in the same event?

In [9]:
pd.read_sql_query("SELECT * FROM athlete WHERE Height > (SELECT AVG(Height) FROM athlete WHERE Year=2008) AND Year=2008 AND Medal='Gold'", con=con)

C:\Users\HP\AppData\Local\Temp\ipykernel_52936\4266118944.py:1: UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.
  pd.read_sql_query("SELECT * FROM athlete WHERE Height > (SELECT AVG(Height) FROM athlete WHERE Year=2008) AND Year=2008 AND Medal='Gold'", con=con)

,ID,Name,Sex,Age,Height,Weight,Team,NOC,Games,Year,Season,City,Sport,Event,Medal
0,72,Aleksey Aleksandrovich Abalmasov,M,28.0,180.0,83.0,Belarus,BLR,2008 Summer,2008,Summer,Beijing,Canoeing,"Canoeing Men's Kayak Fours, 1,000 metres",Gold
1,73,Luc Abalo,M,23.0,182.0,86.0,France,FRA,2008 Summer,2008,Summer,Beijing,Handball,Handball Men's Handball,Gold
2,93,Jol Marc Abati,M,38.0,190.0,85.0,France,FRA,2008 Summer,2008,Summer,Beijing,Handball,Handball Men's Handball,Gold
3,583,Julien Absalon,M,27.0,180.0,68.0,France,FRA,2008 Summer,2008,Summer,Beijing,Cycling,"Cycling Men's Mountainbike, Cross-Country",Gold
4,846,Valerie Kasanita Adams-Vili (-Price),F,23.0,193.0,120.0,New Zealand,NZL,2008 Summer,2008,Summer,Beijing,Athletics,Athletics Women's Shot Put,Gold
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
357,134286,Christopher Zeller,M,23.0,185.0,89.0,Germany,GER,2008 Summer,2008,Summer,Beijing,Hockey,Hockey Men's Hockey,Gold
358,134288,Philipp Zeller,M,25.0,183.0,87.0,Germany,GER,2008 Summer,2008,Summer,Beijing,Hockey,Hockey Men's Hockey,Gold
359,134572,Zhang Xiaoping,M,26.0,188.0,81.0,China,CHN,2008 Summer,2008,Summer,Beijing,Boxing,Boxing Men's Light-Heavyweight,Gold
360,134592,Zhang Yangyang,F,19.0,185.0,80.0,China,CHN,2008 Summer,2008,Summer,Beijing,Rowing,Rowing Women's Quadruple Sculls,Gold
361,134781,Zhong Man,M,25.0,190.0,75.0,China,CHN,2008 Summer,2008,Summer,Beijing,Fencing,"Fencing Men's Sabre, Individual",Gold

In [10]:
pd.read_sql_query("SELECT name FROM athlete WHERE Weight > (SELECT AVG(Weight) FROM athlete WHERE Year=2016 AND Medal IS NOT null) AND Year=2008 AND Medal IS NOT null AND Sport='Basketball'", con=con)

C:\Users\HP\AppData\Local\Temp\ipykernel_52936\446405978.py:1: UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.
  pd.read_sql_query("SELECT name FROM athlete WHERE Weight > (SELECT AVG(Weight) FROM athlete WHERE Year=2016 AND Medal IS NOT null) AND Year=2008 AND Medal IS NOT null AND Sport='Basketball'", con=con)

                                    name
0           Svetlana Olegovna Abrosimova
1                   Carmelo Kyan Anthony
2               Seimone Delicia Augustus
3                 Suzy Batkovic (-Brown)
4              Carlos Austin Boozer, Jr.
5        Christopher Wesson "Chris" Bosh
6                       Kobe Bean Bryant
7            Jos Manuel Caldern Borrallo
8               Tamika Devonne Catchings
9                            Rohanee Cox
10              Carlos Francisco Delfino
11         Rodolfo "Rudy" Fernndez Farrs
12               Sylvia Shaqueria Fowles
13       Jorge Joaqun Garbajosa Chaparro
14                        Marc Gasol Sez
15                         Pau Gasol Sez
16  Emanuel David "Manu" Ginbili Maccari
17                   Romn Javier Gonzlez
18       Hollie Louise Grima (-Florance)
19            Juan Pedro Gutirrez Llanas
20               Leonardo Martn Gutirrez
21                   Dwight David Howard
22              Lauren Elizabeth Jackson
23                  LeBron Raymone James
24                  Carlos Jimnez Snchez
25         Guillermo Federico Kammerichs
26                  Jason Frederick Kidd
27          Marina Vyacheslavovna Kuzina
28                     Kara Marie Lawson
29       Lisa Deshawn Leslie (-Lockwood)
30          Yekaterina Viktorovna Lisina
31                       Ral Lpez Molist
32          DeLisha Lachell Milton-Jones
33                      lex Mumbr Murcia
34            Juan Carlos Navarro Feijoo
35            Andrs Marcelo Nocioni Roux
36              Fabricio Ral Jess Oberto
37     Candace Nicole Parker (-Williams)
38     Christopher Emmanuel "Chris" Paul
39    Antonio Alejandro Porta Pernigotti
40                        Pablo Prigioni
41                Tayshaun Durell Prince
42               Alfredo Paolo Quinteros
43              Emma Randall (-McDonald)
44                   Michael Wesley Redd
45                   Felipe Reyes Cabaas
46       Bernardo "Berni" Rodrguez Arias
47            Ricard "Ricky" Rubio Vives
48             Luis Alberto Scola Balvoa
49           Katherine May "Katie" Smith
50                    Belinda Rose Snell
51        Mariya Aleksandrovna Stepanova
52            Laura Ann Summerton-Hodges
53                   Tina Marie Thompson
54    Nataliya Aleksandrovna Vodopyanova
55               Dwyane Tyrone Wade, Jr.
56                Deron Michael Williams

In [11]:
pd.read_sql_query("SELECT name FROM athlete WHERE Medal IS NOT null AND Year IN (2008, 2016) AND Sport='Swimming'", con=con)

C:\Users\HP\AppData\Local\Temp\ipykernel_52936\3212936711.py:1: UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.
  pd.read_sql_query("SELECT name FROM athlete WHERE Medal IS NOT null AND Year IN (2008, 2016) AND Sport='Swimming'", con=con)

                           name
0          Matthew "Matt" Abood
1     Rebecca "Becky" Adlington
2     Rebecca "Becky" Adlington
3        Nathan Ghar-Jun Adrian
4        Nathan Ghar-Jun Adrian
..                          ...
386  Yuliya Andreyevna Yefimova
387                   Zhang Lin
388                   Zhao Jing
389                  Zhou Yafei
390                 Zhu Qianwei

[391 rows x 1 columns]

In [14]:
pd.read_sql_query("SELECT Team FROM athlete WHERE Medal IS NOT null GROUP BY Year HAVING COUNT(*) > 50", con=con)

C:\Users\HP\AppData\Local\Temp\ipykernel_52936\289405191.py:1: UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.
  pd.read_sql_query("SELECT Team FROM athlete WHERE Medal IS NOT null GROUP BY Year HAVING COUNT(*) > 50", con=con)

                Team
0             Greece
1     Denmark/Sweden
2   Vesper Boat Club
3      Thessalonki-1
4             Sweden
5             Taifun
6            Finland
7        Switzerland
8             Sweden
9      United States
10           Hungary
11           Finland
12           Finland
13            France
14            Norway
15          Pakistan
16      Soviet Union
17      Soviet Union
18       New Zealand
19             Spain
20             Spain
21       Netherlands
22            Norway
23            Norway
24       Netherlands
25            Russia
26          Cameroon
27            Norway
28     United States
29            Norway
30            Norway
31         Germany-2
32            France
33           Finland
34             Italy

In [4]:

pd.read_sql_query("SELECT Name FROM (SELECT Name, Year FROM athlete WHERE Medal IS NOT null GROUP BY Name, Year HAVING COUNT(DISTINCT Sport)>1) AS tab", con=con)

C:\Users\HP\AppData\Local\Temp\ipykernel_45496\1066441356.py:1: UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.
  pd.read_sql_query("SELECT Name FROM (SELECT Name, Year FROM athlete WHERE Medal IS NOT null GROUP BY Name, Year HAVING COUNT(DISTINCT Sport)>1) AS tab", con=con)

                                          Name
0                Aileen Muriel Riggin (-Soule)
1                Aleksandr Vladimirovich Popov
2                       Alexander Viggo Jensen
3                    Amedee Valle Reyburn, Jr.
4                               Carl Schuhmann
5         Charles Marius Duma Adolphe Gondouin
6                  Christa Rothenburger-Luding
7                       David Thurwell Hammond
8                           Dsir Alfred Mrchez
9                         Edward "Ned" Barrett
10                  Edwin Harold "Teddy" Flack
11                  Eric Otto Valdemar Lemming
12                              Frank D. Kehoe
13                             Frank X. Kugler
14               Fritz Albert Erich Rademacher
15                               Fritz Hofmann
16                              Georg Hoffmann
17                            Grard Blitz, Jr.
18                                Gwynne Evans
19                         Heikki Vihtori Hasu
20                              Heinrich Rondi
21                       Heinrich Schneidereit
22                        Hjrdis Viktoria Tpel
23                        Holger Louis Nielsen
24              James Wallace "Wally" O'Connor
25                                 Jean Collas
26                             Jennison Heaton
27       Johan Hagbart Pedersen Grttumsbraaten
28       Johan Hagbart Pedersen Grttumsbraaten
29                          John Arthur Jarvis
30            Joseph Aloysius "Joe" Ruddy, Sr.
31                             Joseph De Combe
32                  Joseph Patrick "Joe" Lydon
33  Katherine Louise Rawls (-Thompson, -Green)
34                                  Lajos Szcs
35                   Leo Joseph "Budd" Goodwin
36                                       Li Na
37                                     Li Ting
38                Louis de Breda "Lou" Handley
39                                Louis Martin
40                         mile Pierre Sarrade
41                     Morris Marshall Kirksey
42                               Oddbjrn Hagen
43                            Olaf Hoffsbakken
44          Paolo Francesco "Paul"  Radmilovic
45                Patrik Georg Fabian de Laval
46           Peter Johann "Johnny" Weissmuller
47                                  Peter Kemp
48                               Pontus Hanson
49              Sigfrid Harald Alexander Julin
50                             Sotirios Versis
51                             Stefan Dimitrov
52                              Sverre Brodahl
53                            Thoralf Strmstad
54                    Thorleif Haug (Johnsen-)
55                               Walter Winans
56                                    Wang Hao
57              William Jeremiah "Bill" Tuttle
58              William Robert "Bill" Orthwein
59                                    Yang Wei

In [10]:

a = "SELECT AVG(weight_difference) AS average_weight_difference FROM(SELECT Sport, AVG(CASE WHEN Sex = 'M' THEN Weight END) - AVG(CASE WHEN Sex = 'F' THEN Weight END) AS weight_difference FROM athlete WHERE Medal IS NOT NULL GROUP BY Sport) AS result"

pd.read_sql_query(a, con=con)

C:\Users\HP\AppData\Local\Temp\ipykernel_45496\590448737.py:3: UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.
  pd.read_sql_query(a, con=con)

   average_weight_difference
0                  15.591451